/**
 * Sync Schema Index
 *
 * Barrel export for all schema definitions.
 * 
 * Entity DDL is generated by drizzle-sync from the backend schema.
 * Sync infrastructure tables (sync_operations, sync_dead_letter) are managed manually.
 */

import type { PGlite } from "@electric-sql/pglite";

const LEGACY_ENTITY_TYPE_ALIASES: Record<string, string> = {
  saleItems: "sale_items",
  purchaseItems: "purchase_items",
  productVariants: "product_variants",
  customerTags: "customer_tags",
  customerGroups: "customer_groups",
  customerGroupMembers: "customer_group_members",
  distribucionItems: "distribucion_items",
};

const LEGACY_ENTITY_TYPE_MAPPINGS = Object.entries(LEGACY_ENTITY_TYPE_ALIASES);

// Re-export sync table schemas (sync infrastructure - not generated)
export {
  SCHEMA_NAME,
  CREATE_SYNC_OPERATIONS_TABLE,
  ALTER_SYNC_OPERATIONS_TABLE,
  CREATE_SYNC_OPERATIONS_INDEXES,
  FULL_SCHEMA as SYNC_OPERATIONS_FULL_SCHEMA,
} from "./sync-operations.schema";

export {
  SCHEMA_NAME as DEAD_LETTER_SCHEMA_NAME,
  CREATE_SYNC_DEAD_LETTER_TABLE,
  ALTER_SYNC_DEAD_LETTER_TABLE,
  CREATE_SYNC_DEAD_LETTER_INDEXES,
  FULL_SCHEMA as SYNC_DEAD_LETTER_FULL_SCHEMA,
} from "./sync-dead-letter.schema";

// Re-export entity schemas from generated DDL (backward compatibility exports)
export { SCHEMA_NAME as CUSTOMERS_SCHEMA_NAME } from "./customers.schema";
export { SCHEMA_NAME as SALES_SCHEMA_NAME } from "./sales.schema";
export { SCHEMA_NAME as SALE_ITEMS_SCHEMA_NAME } from "./sale-items.schema";
export { SCHEMA_NAME as ABONOS_SCHEMA_NAME } from "./abonos.schema";
export { SCHEMA_NAME as PRODUCTS_SCHEMA_NAME } from "./products.schema";
export { SCHEMA_NAME as PRODUCT_VARIANTS_SCHEMA_NAME } from "./product-variants.schema";
export { SCHEMA_NAME as SUPPLIERS_SCHEMA_NAME } from "./suppliers.schema";
export { SCHEMA_NAME as PURCHASES_SCHEMA_NAME } from "./purchases.schema";
export { SCHEMA_NAME as PURCHASE_ITEMS_SCHEMA_NAME } from "./purchase-items.schema";
export { SCHEMA_NAME as DISTRIBUCIONES_SCHEMA_NAME } from "./distribuciones.schema";
export { SCHEMA_NAME as DISTRIBUCION_ITEMS_SCHEMA_NAME } from "./distribucion-items.schema";
export { SCHEMA_NAME as TAGS_SCHEMA_NAME } from "./tags.schema";
export { SCHEMA_NAME as CUSTOMER_TAGS_SCHEMA_NAME } from "./customer-tags.schema";
export { SCHEMA_NAME as VARIANT_INVENTORY_SCHEMA_NAME } from "./variant-inventory.schema";
export { SCHEMA_NAME as VISITAS_SCHEMA_NAME } from "./visitas.schema";
export { SCHEMA_NAME as CUSTOMER_GROUPS_SCHEMA_NAME } from "./customer-groups.schema";
export { SCHEMA_NAME as CUSTOMER_GROUP_MEMBERS_SCHEMA_NAME } from "./customer-group-members.schema";

// Import sync infrastructure schemas
import {
  CREATE_SYNC_OPERATIONS_TABLE,
  ALTER_SYNC_OPERATIONS_TABLE,
  CREATE_SYNC_OPERATIONS_INDEXES,
} from "./sync-operations.schema";

import {
  CREATE_SYNC_DEAD_LETTER_TABLE,
  ALTER_SYNC_DEAD_LETTER_TABLE,
  CREATE_SYNC_DEAD_LETTER_INDEXES,
} from "./sync-dead-letter.schema";

// Import generated entity DDL
// The init.sql file contains all entity CREATE TABLE and CREATE INDEX statements
import GENERATED_ENTITY_SCHEMA from "../generated/init.sql?raw";

/**
 * Combined full schema SQL (all CREATE TABLE + ALTER + INDEX)
 * Uses generated DDL for entities, manual DDL for sync infrastructure
 */
export const FULL_SCHEMA = [
  GENERATED_ENTITY_SCHEMA,
  CREATE_SYNC_OPERATIONS_TABLE,
  ALTER_SYNC_OPERATIONS_TABLE,
  CREATE_SYNC_OPERATIONS_INDEXES,
  CREATE_SYNC_DEAD_LETTER_TABLE,
  ALTER_SYNC_DEAD_LETTER_TABLE,
  CREATE_SYNC_DEAD_LETTER_INDEXES,
].join("\n");

/**
 * Combined schema SQL (CREATE TABLE + INDEX only, no ALTER)
 * Uses generated DDL for entities, manual DDL for sync infrastructure
 */
export const SCHEMA_NO_ALTER = [
  GENERATED_ENTITY_SCHEMA,
  CREATE_SYNC_OPERATIONS_TABLE,
  CREATE_SYNC_OPERATIONS_INDEXES,
  CREATE_SYNC_DEAD_LETTER_TABLE,
  CREATE_SYNC_DEAD_LETTER_INDEXES,
].join("\n");

/**
 * Initialize all sync tables (sync infrastructure)
 */
export async function initSyncTables(pg: PGlite): Promise<void> {
  await pg.exec(CREATE_SYNC_OPERATIONS_TABLE);
  await pg.exec(ALTER_SYNC_OPERATIONS_TABLE);
  await pg.exec(CREATE_SYNC_OPERATIONS_INDEXES);

  await pg.exec(CREATE_SYNC_DEAD_LETTER_TABLE);
  await pg.exec(ALTER_SYNC_DEAD_LETTER_TABLE);
  await pg.exec(CREATE_SYNC_DEAD_LETTER_INDEXES);
}

/**
 * Initialize all entity tables using generated DDL
 */
export async function initEntityTables(pg: PGlite): Promise<void> {
  // Execute the generated entity DDL (includes all CREATE TABLE and CREATE INDEX)
  await pg.exec(GENERATED_ENTITY_SCHEMA);
}

/**
 * Initialize all tables (entities + sync)
 */
export async function initAllTables(pg: PGlite): Promise<void> {
  await initEntityTables(pg);
  await initSyncTables(pg);
}

/**
 * Ensure sync-specific tables and indexes exist and backfill business ownership
 * for legacy records created before business_id was enforced.
 */
export async function ensureSyncSchema(
  pg: PGlite,
  businessId?: string
): Promise<void> {
  await initSyncTables(pg);

  if (!businessId) {
    return;
  }

  await pg.query(
    `UPDATE sync_operations
     SET business_id = $1
     WHERE business_id IS NULL`,
    [businessId]
  );

  await pg.query(
    `UPDATE sync_dead_letter
     SET business_id = $1
     WHERE business_id IS NULL`,
    [businessId]
  );
}

/**
 * Normalize legacy camelCase entity names to canonical snake_case.
 *
 * Idempotent: if rows are already canonical, updates are no-ops.
 */
export async function normalizeLegacySyncEntityTypes(pg: PGlite): Promise<void> {
  for (const [legacyEntityType, canonicalEntityType] of LEGACY_ENTITY_TYPE_MAPPINGS) {
    await pg.query(
      `UPDATE sync_operations
       SET entity_type = $1,
           updated_at = CURRENT_TIMESTAMP
       WHERE entity_type = $2`,
      [canonicalEntityType, legacyEntityType]
    );

    await pg.query(
      `UPDATE sync_dead_letter
       SET entity_type = $1
       WHERE entity_type = $2`,
      [canonicalEntityType, legacyEntityType]
    );
  }
}
