/**
 * Sync Schema Index
 *
 * Barrel export for all schema definitions.
 */

import type { PGlite } from "@electric-sql/pglite";

// Re-export sync table schemas
export {
  SCHEMA_NAME,
  CREATE_SYNC_OPERATIONS_TABLE,
  ALTER_SYNC_OPERATIONS_TABLE,
  CREATE_SYNC_OPERATIONS_INDEXES,
  FULL_SCHEMA as SYNC_OPERATIONS_FULL_SCHEMA,
} from "./sync-operations.schema";

export {
  SCHEMA_NAME as DEAD_LETTER_SCHEMA_NAME,
  CREATE_SYNC_DEAD_LETTER_TABLE,
  ALTER_SYNC_DEAD_LETTER_TABLE,
  CREATE_SYNC_DEAD_LETTER_INDEXES,
  FULL_SCHEMA as SYNC_DEAD_LETTER_FULL_SCHEMA,
} from "./sync-dead-letter.schema";

// Re-export entity schemas
export { SCHEMA_NAME as CUSTOMERS_SCHEMA_NAME, CREATE_CUSTOMERS_TABLE, CREATE_CUSTOMERS_INDEXES } from "./customers.schema";
export { SCHEMA_NAME as SALES_SCHEMA_NAME, CREATE_SALES_TABLE, CREATE_SALES_INDEXES } from "./sales.schema";
export { SCHEMA_NAME as SALE_ITEMS_SCHEMA_NAME, CREATE_SALE_ITEMS_TABLE, CREATE_SALE_ITEMS_INDEXES } from "./sale-items.schema";
export { SCHEMA_NAME as ABONOS_SCHEMA_NAME, CREATE_ABONOS_TABLE, CREATE_ABONOS_INDEXES } from "./abonos.schema";
export { SCHEMA_NAME as PRODUCTS_SCHEMA_NAME, CREATE_PRODUCTS_TABLE, CREATE_PRODUCTS_INDEXES } from "./products.schema";
export { SCHEMA_NAME as PRODUCT_VARIANTS_SCHEMA_NAME, CREATE_PRODUCT_VARIANTS_TABLE, CREATE_PRODUCT_VARIANTS_INDEXES } from "./product-variants.schema";
export { SCHEMA_NAME as SUPPLIERS_SCHEMA_NAME, CREATE_SUPPLIERS_TABLE, CREATE_SUPPLIERS_INDEXES } from "./suppliers.schema";
export { SCHEMA_NAME as PURCHASES_SCHEMA_NAME, CREATE_PURCHASES_TABLE, CREATE_PURCHASES_INDEXES } from "./purchases.schema";
export { SCHEMA_NAME as PURCHASE_ITEMS_SCHEMA_NAME, CREATE_PURCHASE_ITEMS_TABLE, CREATE_PURCHASE_ITEMS_INDEXES } from "./purchase-items.schema";
export { SCHEMA_NAME as DISTRIBUCIONES_SCHEMA_NAME, CREATE_DISTRIBUCIONES_TABLE, CREATE_DISTRIBUCIONES_INDEXES } from "./distribuciones.schema";
export { SCHEMA_NAME as DISTRIBUCION_ITEMS_SCHEMA_NAME, CREATE_DISTRIBUCION_ITEMS_TABLE, CREATE_DISTRIBUCION_ITEMS_INDEXES } from "./distribucion-items.schema";
export { SCHEMA_NAME as TAGS_SCHEMA_NAME, CREATE_TAGS_TABLE, CREATE_TAGS_INDEXES } from "./tags.schema";
export { SCHEMA_NAME as CUSTOMER_TAGS_SCHEMA_NAME, CREATE_CUSTOMER_TAGS_TABLE, CREATE_CUSTOMER_TAGS_INDEXES } from "./customer-tags.schema";
export { SCHEMA_NAME as VARIANT_INVENTORY_SCHEMA_NAME, CREATE_VARIANT_INVENTORY_TABLE, CREATE_VARIANT_INVENTORY_INDEXES } from "./variant-inventory.schema";
export { SCHEMA_NAME as VISITAS_SCHEMA_NAME, CREATE_VISITAS_TABLE, CREATE_VISITAS_INDEXES } from "./visitas.schema";
export { SCHEMA_NAME as CUSTOMER_GROUPS_SCHEMA_NAME, CREATE_CUSTOMER_GROUPS_TABLE, CREATE_CUSTOMER_GROUPS_INDEXES } from "./customer-groups.schema";
export { SCHEMA_NAME as CUSTOMER_GROUP_MEMBERS_SCHEMA_NAME, CREATE_CUSTOMER_GROUP_MEMBERS_TABLE, CREATE_CUSTOMER_GROUP_MEMBERS_INDEXES } from "./customer-group-members.schema";

// Import schemas for combined export
import {
  CREATE_SYNC_OPERATIONS_TABLE,
  ALTER_SYNC_OPERATIONS_TABLE,
  CREATE_SYNC_OPERATIONS_INDEXES,
} from "./sync-operations.schema";

import {
  CREATE_SYNC_DEAD_LETTER_TABLE,
  ALTER_SYNC_DEAD_LETTER_TABLE,
  CREATE_SYNC_DEAD_LETTER_INDEXES,
} from "./sync-dead-letter.schema";

import { CREATE_CUSTOMERS_TABLE, CREATE_CUSTOMERS_INDEXES } from "./customers.schema";
import { CREATE_SALES_TABLE, CREATE_SALES_INDEXES } from "./sales.schema";
import { CREATE_SALE_ITEMS_TABLE, CREATE_SALE_ITEMS_INDEXES } from "./sale-items.schema";
import { CREATE_ABONOS_TABLE, CREATE_ABONOS_INDEXES } from "./abonos.schema";
import { CREATE_PRODUCTS_TABLE, CREATE_PRODUCTS_INDEXES } from "./products.schema";
import { CREATE_PRODUCT_VARIANTS_TABLE, CREATE_PRODUCT_VARIANTS_INDEXES } from "./product-variants.schema";
import { CREATE_SUPPLIERS_TABLE, CREATE_SUPPLIERS_INDEXES } from "./suppliers.schema";
import { CREATE_PURCHASES_TABLE, CREATE_PURCHASES_INDEXES } from "./purchases.schema";
import { CREATE_PURCHASE_ITEMS_TABLE, CREATE_PURCHASE_ITEMS_INDEXES } from "./purchase-items.schema";
import { CREATE_DISTRIBUCIONES_TABLE, CREATE_DISTRIBUCIONES_INDEXES } from "./distribuciones.schema";
import { CREATE_DISTRIBUCION_ITEMS_TABLE, CREATE_DISTRIBUCION_ITEMS_INDEXES } from "./distribucion-items.schema";
import { CREATE_TAGS_TABLE, CREATE_TAGS_INDEXES } from "./tags.schema";
import { CREATE_CUSTOMER_TAGS_TABLE, CREATE_CUSTOMER_TAGS_INDEXES } from "./customer-tags.schema";
import { CREATE_VARIANT_INVENTORY_TABLE, CREATE_VARIANT_INVENTORY_INDEXES } from "./variant-inventory.schema";
import { CREATE_VISITAS_TABLE, CREATE_VISITAS_INDEXES } from "./visitas.schema";
import { CREATE_CUSTOMER_GROUPS_TABLE, CREATE_CUSTOMER_GROUPS_INDEXES } from "./customer-groups.schema";
import { CREATE_CUSTOMER_GROUP_MEMBERS_TABLE, CREATE_CUSTOMER_GROUP_MEMBERS_INDEXES } from "./customer-group-members.schema";

/**
 * All CREATE TABLE statements
 */
const CREATE_TABLES = [
  CREATE_CUSTOMERS_TABLE,
  CREATE_SALES_TABLE,
  CREATE_SALE_ITEMS_TABLE,
  CREATE_ABONOS_TABLE,
  CREATE_PRODUCTS_TABLE,
  CREATE_PRODUCT_VARIANTS_TABLE,
  CREATE_SUPPLIERS_TABLE,
  CREATE_PURCHASES_TABLE,
  CREATE_PURCHASE_ITEMS_TABLE,
  CREATE_DISTRIBUCIONES_TABLE,
  CREATE_DISTRIBUCION_ITEMS_TABLE,
  CREATE_TAGS_TABLE,
  CREATE_CUSTOMER_TAGS_TABLE,
  CREATE_VARIANT_INVENTORY_TABLE,
  CREATE_VISITAS_TABLE,
  CREATE_CUSTOMER_GROUPS_TABLE,
  CREATE_CUSTOMER_GROUP_MEMBERS_TABLE,
  CREATE_SYNC_OPERATIONS_TABLE,
  CREATE_SYNC_DEAD_LETTER_TABLE,
];

/**
 * All ALTER TABLE statements
 */
const ALTER_TABLES = [
  ALTER_SYNC_OPERATIONS_TABLE,
  ALTER_SYNC_DEAD_LETTER_TABLE,
];

/**
 * All CREATE INDEX statements
 */
const CREATE_INDEXES = [
  CREATE_CUSTOMERS_INDEXES,
  CREATE_SALES_INDEXES,
  CREATE_SALE_ITEMS_INDEXES,
  CREATE_ABONOS_INDEXES,
  CREATE_PRODUCTS_INDEXES,
  CREATE_PRODUCT_VARIANTS_INDEXES,
  CREATE_SUPPLIERS_INDEXES,
  CREATE_PURCHASES_INDEXES,
  CREATE_PURCHASE_ITEMS_INDEXES,
  CREATE_DISTRIBUCIONES_INDEXES,
  CREATE_DISTRIBUCION_ITEMS_INDEXES,
  CREATE_TAGS_INDEXES,
  CREATE_CUSTOMER_TAGS_INDEXES,
  CREATE_VARIANT_INVENTORY_INDEXES,
  CREATE_VISITAS_INDEXES,
  CREATE_CUSTOMER_GROUPS_INDEXES,
  CREATE_CUSTOMER_GROUP_MEMBERS_INDEXES,
  CREATE_SYNC_OPERATIONS_INDEXES,
  CREATE_SYNC_DEAD_LETTER_INDEXES,
];

/**
 * Combined full schema SQL (all CREATE TABLE + ALTER + INDEX)
 */
export const FULL_SCHEMA = [
  ...CREATE_TABLES,
  ...ALTER_TABLES,
  ...CREATE_INDEXES,
].join("\n");

/**
 * Combined schema SQL (CREATE TABLE + INDEX only, no ALTER)
 */
export const SCHEMA_NO_ALTER = [
  ...CREATE_TABLES,
  ...CREATE_INDEXES,
].join("\n");

/**
 * Initialize all sync tables
 */
export async function initSyncTables(pg: PGlite): Promise<void> {
  await pg.exec(CREATE_SYNC_OPERATIONS_TABLE);
  await pg.exec(ALTER_SYNC_OPERATIONS_TABLE);
  await pg.exec(CREATE_SYNC_OPERATIONS_INDEXES);

  await pg.exec(CREATE_SYNC_DEAD_LETTER_TABLE);
  await pg.exec(ALTER_SYNC_DEAD_LETTER_TABLE);
  await pg.exec(CREATE_SYNC_DEAD_LETTER_INDEXES);
}

/**
 * Initialize all entity tables
 */
export async function initEntityTables(pg: PGlite): Promise<void> {
  for (const table of CREATE_TABLES) {
    await pg.exec(table);
  }
  for (const indexes of CREATE_INDEXES) {
    await pg.exec(indexes);
  }
}

/**
 * Initialize all tables (entities + sync)
 */
export async function initAllTables(pg: PGlite): Promise<void> {
  await initEntityTables(pg);
  await initSyncTables(pg);
}
