import type { ColumnMetadata, GeneratedApplierConfig } from "../../config/types";
import { camelCase } from "../../utils/string-utils";
import { CodeBuilder } from "./code-builder";
import {
  extractTableName,
  getAllColumns,
  type GeneratorEntity,
} from "./schema-adapter";

export function generateApplierConfig(
  entityName: string,
  entity: GeneratorEntity
): GeneratedApplierConfig {
  const tableName = extractTableName(entityName, entity);
  const columns = getAllColumns(entity);

  const columnNames = columns.map((c) => c.name);

  if (!columnNames.includes("sync_status")) {
    columnNames.push("sync_status");
  }
  if (!columnNames.includes("sync_attempts")) {
    columnNames.push("sync_attempts");
  }

  const defaults: Record<string, unknown> = {};
  for (const col of columns) {
    if (col.notNull && !col.hasDefault) {
      const defaultValue = inferDefaultForType(col.dataType);
      if (defaultValue !== undefined) {
        defaults[col.name] = defaultValue;
      }
    }
  }

  defaults.sync_status = "synced";
  defaults.sync_attempts = 0;

  return {
    validTables: new Set([tableName]),
    tableColumns: {
      [tableName]: new Set(columnNames),
    },
    requiredDefaults: Object.keys(defaults).length > 0 ? { [tableName]: defaults } : undefined,
    relationFields: new Set(detectRelationFields(columns)),
  };
}

function inferDefaultForType(dataType: ColumnMetadata["dataType"]): unknown | undefined {
  switch (dataType) {
    case "string":
      return "";
    case "number":
      return 0;
    case "boolean":
      return false;
    case "date":
      return new Date().toISOString();
    case "json":
      return {};
    default:
      return undefined;
  }
}

function detectRelationFields(columns: ColumnMetadata[]): string[] {
  const relations: string[] = [];
  const relationPatterns = ["items", "customer", "seller", "business", "product", "variant", "supplier"];

  for (const col of columns) {
    const camelName = camelCase(col.name);
    if (relationPatterns.some((pattern) => camelName.toLowerCase() === pattern.toLowerCase())) {
      relations.push(camelName);
    }
  }

  return relations;
}

export function mergeApplierConfigs(configs: GeneratedApplierConfig[]): GeneratedApplierConfig {
  const validTables = new Set<string>();
  const tableColumns: Record<string, Set<string>> = {};
  const requiredDefaults: Record<string, Record<string, unknown>> = {};
  const relationFields = new Set<string>();

  for (const config of configs) {
    config.validTables.forEach((t) => validTables.add(t));
    Object.assign(tableColumns, config.tableColumns);
    if (config.requiredDefaults) {
      Object.assign(requiredDefaults, config.requiredDefaults);
    }
    if (config.relationFields) {
      config.relationFields.forEach((f) => relationFields.add(f));
    }
  }

  return {
    validTables,
    tableColumns,
    requiredDefaults: Object.keys(requiredDefaults).length > 0 ? requiredDefaults : undefined,
    relationFields: relationFields.size > 0 ? relationFields : undefined,
  };
}

export function generateApplierFile(config: GeneratedApplierConfig, applyOrder?: string[]): string {
  const b = new CodeBuilder();
  const requiredDefaults = config.requiredDefaults ?? {};

  b.line("// AUTO-GENERATED FILE - DO NOT EDIT");
  b.line("// Generated by drizzle-sync from backend schema");
  b.blank();
  b.line('import type { ChangeApplierConfig } from "@avileo/drizzle-sync/pglite";');
  b.blank();

  b.line("export const VALID_TABLES = new Set([");
  b.indent((ib) => {
    config.validTables.forEach((t) => ib.line(`"${t}",`));
  });
  b.line("]);" );
  b.blank();

  b.line("export const TABLE_COLUMNS: Record<string, Set<string>> = {");
  b.indent((ib) => {
    for (const [tableName, columns] of Object.entries(config.tableColumns)) {
      ib.line(`${tableName}: new Set([`);
      ib.indent((iib) => {
        columns.forEach((col) => iib.line(`"${col}",`));
      });
      ib.line("]),");
    }
  });
  b.line("};");
  b.blank();

  if (Object.keys(requiredDefaults).length > 0) {
    b.line("export const REQUIRED_COLUMN_DEFAULTS: Record<string, Record<string, unknown>> = {");
    b.indent((ib) => {
      for (const [tableName, defaults] of Object.entries(requiredDefaults)) {
        ib.line(`${tableName}: {`);
        ib.indent((iib) => {
          for (const [col, val] of Object.entries(defaults)) {
            iib.line(`${col}: ${JSON.stringify(val)},`);
          }
        });
        ib.line("},");
      }
    });
    b.line("};");
    b.blank();
  }

  if (config.relationFields && config.relationFields.size > 0) {
    b.line("export const RELATION_FIELDS = new Set([");
    b.indent((ib) => {
      config.relationFields?.forEach((f) => ib.line(`"${f}",`));
    });
    b.line("]);" );
    b.blank();
  }

  if (applyOrder && applyOrder.length > 0) {
    b.line("export const APPLY_ORDER = [");
    b.indent((ib) => {
      applyOrder.forEach((t) => ib.line(`"${t}",`));
    });
    b.line("];" );
    b.blank();
  }

  b.line("export const applierConfig: ChangeApplierConfig = {");
  b.indent((ib) => {
    ib.line("validTables: VALID_TABLES,");
    ib.line("tableColumns: TABLE_COLUMNS,");
    if (config.requiredDefaults) ib.line("requiredDefaults: REQUIRED_COLUMN_DEFAULTS,");
    if (config.relationFields) ib.line("relationFields: RELATION_FIELDS,");
    if (applyOrder) ib.line("applyOrder: APPLY_ORDER,");
  });
  b.line("};");
  b.blank();
  b.line("export default applierConfig;");

  return b.toString();
}
