import { camelCase } from "../../utils/string-utils";
import type { ColumnMetadata, EntitySyncConfig, GeneratedApplierConfig } from "../../config/types";
import { introspectTable, resolveColumns } from "../../config/introspect";

export function generateApplierConfig(
  entityName: string,
  config: EntitySyncConfig
): GeneratedApplierConfig {
  const columns = introspectTable(config.table);
  const columnsToInclude = resolveColumns(columns, config);

  const columnNames = columnsToInclude.map((c) => c.name);

  if (!columnNames.includes("sync_status")) {
    columnNames.push("sync_status");
  }
  if (!columnNames.includes("sync_attempts")) {
    columnNames.push("sync_attempts");
  }

  const defaults: Record<string, unknown> = {};
  for (const col of columnsToInclude) {
    if (col.notNull && col.default === undefined) {
      const defaultValue = inferDefaultForType(col.dataType);
      if (defaultValue !== undefined) {
        defaults[col.name] = defaultValue;
      }
    }
  }

  defaults["sync_status"] = "synced";
  defaults["sync_attempts"] = 0;

  return {
    validTables: new Set([entityName]),
    tableColumns: {
      [entityName]: new Set(columnNames),
    },
    requiredDefaults: Object.keys(defaults).length > 0 ? { [entityName]: defaults } : undefined,
    relationFields: new Set(detectRelationFields(columns)),
  };
}

function inferDefaultForType(dataType: ColumnMetadata["dataType"]): unknown | undefined {
  switch (dataType) {
    case "string":
      return "";
    case "number":
      return 0;
    case "boolean":
      return false;
    case "date":
      return new Date().toISOString();
    case "json":
      return {};
    default:
      return undefined;
  }
}

function detectRelationFields(columns: ColumnMetadata[]): string[] {
  const relations: string[] = [];
  const relationPatterns = ["items", "customer", "seller", "business", "product", "variant", "supplier"];

  for (const col of columns) {
    const camelName = camelCase(col.name);
    if (relationPatterns.some((pattern) => camelName.toLowerCase() === pattern.toLowerCase())) {
      relations.push(camelName);
    }
  }

  return relations;
}

export function mergeApplierConfigs(configs: GeneratedApplierConfig[]): GeneratedApplierConfig {
  const validTables = new Set<string>();
  const tableColumns: Record<string, Set<string>> = {};
  const requiredDefaults: Record<string, Record<string, unknown>> = {};
  const relationFields = new Set<string>();

  for (const config of configs) {
    config.validTables.forEach((t) => validTables.add(t));
    Object.assign(tableColumns, config.tableColumns);
    if (config.requiredDefaults) {
      Object.assign(requiredDefaults, config.requiredDefaults);
    }
    if (config.relationFields) {
      config.relationFields.forEach((f) => relationFields.add(f));
    }
  }

  return {
    validTables,
    tableColumns,
    requiredDefaults: Object.keys(requiredDefaults).length > 0 ? requiredDefaults : undefined,
    relationFields: relationFields.size > 0 ? relationFields : undefined,
  };
}

export function generateApplierFile(config: GeneratedApplierConfig, applyOrder?: string[]): string {
  const lines: string[] = [
    "// AUTO-GENERATED FILE - DO NOT EDIT",
    "// Generated by drizzle-sync from backend schema",
    "",
    "import type { ChangeApplierConfig } from \"@avileo/drizzle-sync/pglite\";",
    "",
    "export const VALID_TABLES = new Set([",
  ];

  config.validTables.forEach((t) => lines.push(`  "${t}",`));
  lines.push("]);");
  lines.push("");

  lines.push("export const TABLE_COLUMNS: Record<string, Set<string>> = {");
  for (const [tableName, columns] of Object.entries(config.tableColumns)) {
    lines.push(`  ${tableName}: new Set([`);
    columns.forEach((col) => lines.push(`    "${col}",`));
    lines.push("  ]),");
  }
  lines.push("};");
  lines.push("");

  if (config.requiredDefaults && Object.keys(config.requiredDefaults).length > 0) {
    lines.push("export const REQUIRED_COLUMN_DEFAULTS: Record<string, Record<string, unknown>> = {");
    for (const [tableName, defaults] of Object.entries(config.requiredDefaults)) {
      lines.push(`  ${tableName}: {`);
      for (const [col, val] of Object.entries(defaults)) {
        lines.push(`    ${col}: ${JSON.stringify(val)},`);
      }
      lines.push("  },");
    }
    lines.push("};");
    lines.push("");
  }

  if (config.relationFields && config.relationFields.size > 0) {
    lines.push("export const RELATION_FIELDS = new Set([");
    config.relationFields.forEach((f) => lines.push(`  "${f}",`));
    lines.push("]);");
    lines.push("");
  }

  if (applyOrder && applyOrder.length > 0) {
    lines.push("export const APPLY_ORDER = [");
    applyOrder.forEach((t) => lines.push(`  "${t}",`));
    lines.push("];");
    lines.push("");
  }

  lines.push("export const applierConfig: ChangeApplierConfig = {");
  lines.push("  validTables: VALID_TABLES,");
  lines.push("  tableColumns: TABLE_COLUMNS,");
  if (config.requiredDefaults) lines.push("  requiredDefaults: REQUIRED_COLUMN_DEFAULTS,");
  if (config.relationFields) lines.push("  relationFields: RELATION_FIELDS,");
  if (applyOrder) lines.push("  applyOrder: APPLY_ORDER,");
  lines.push("};");
  lines.push("");
  lines.push("export default applierConfig;");

  return lines.join("\n");
}
