import type { ColumnMetadata, EntitySyncConfig } from "../../config/types";
import { introspectTable, resolveColumns } from "../../config/introspect";

export interface DDLOutput {
  tableName: string;
  createTable: string;
  indexes: string[];
}

export function generateDDL(entityName: string, config: EntitySyncConfig): DDLOutput {
  const tableName = entityName;
  const columns = introspectTable(config.table);
  const columnsToInclude = resolveColumns(columns, config);

  const columnDefs: string[] = [];

  for (const col of columnsToInclude) {
    const def = columnToSQLiteDef(col);
    columnDefs.push(`  ${def}`);
  }

  if (!columnsToInclude.find((c) => c.name === "sync_status")) {
    columnDefs.push(`  sync_status TEXT NOT NULL DEFAULT 'pending'`);
  }
  if (!columnsToInclude.find((c) => c.name === "sync_attempts")) {
    columnDefs.push(`  sync_attempts INTEGER NOT NULL DEFAULT 0`);
  }

  const primaryKeys = columnsToInclude.filter((c) => c.primary).map((c) => c.name);

  if (primaryKeys.length > 0) {
    columnDefs.push(`  PRIMARY KEY (${primaryKeys.join(", ")})`);
  }

  const createTable = `CREATE TABLE IF NOT EXISTS "${tableName}" (\n${columnDefs.join(",\n")}\n);`;

  const indexes = generateIndexes(tableName, columnsToInclude);

  return {
    tableName,
    createTable,
    indexes,
  };
}

function columnToSQLiteDef(col: ColumnMetadata): string {
  const sqliteType = mapToSQLiteType(col.dataType);
  const nullable = col.notNull ? "NOT NULL" : "";
  const defaultVal = col.default !== undefined ? `DEFAULT ${formatSQLiteDefault(col.default, col.dataType)}` : "";

  const parts = [`"${col.name}"`, sqliteType, nullable, defaultVal].filter(Boolean).join(" ");

  return parts;
}

function mapToSQLiteType(dataType: ColumnMetadata["dataType"]): string {
  switch (dataType) {
    case "string":
      return "TEXT";
    case "number":
      return "INTEGER";
    case "boolean":
      return "INTEGER";
    case "date":
      return "TEXT";
    case "json":
      return "TEXT";
    case "enum":
      return "TEXT";
    default:
      return "TEXT";
  }
}

function formatSQLiteDefault(value: unknown, dataType: ColumnMetadata["dataType"]): string {
  if (value === null) return "NULL";
  if (typeof value === "boolean") return value ? "1" : "0";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return `'${value.replace(/'/g, "''")}'`;
  return "NULL";
}

function generateIndexes(tableName: string, columns: ColumnMetadata[]): string[] {
  const indexes: string[] = [];

  indexes.push(`CREATE INDEX IF NOT EXISTS "idx_${tableName}_sync_status" ON "${tableName}"(sync_status);`);

  if (columns.find((c) => c.name === "business_id")) {
    indexes.push(`CREATE INDEX IF NOT EXISTS "idx_${tableName}_business_id" ON "${tableName}"(business_id);`);
  }

  const fkColumns = columns.filter((c) => c.name.endsWith("_id") && !c.primary);
  for (const col of fkColumns) {
    indexes.push(`CREATE INDEX IF NOT EXISTS "idx_${tableName}_${col.name}" ON "${tableName}"(${col.name});`);
  }

  return indexes;
}

export function generateDDLFile(outputs: DDLOutput[]): string {
  const lines: string[] = [
    "-- AUTO-GENERATED FILE - DO NOT EDIT",
    "-- Generated by drizzle-sync from backend schema",
    "",
    "PRAGMA foreign_keys = ON;",
    "",
  ];

  for (const output of outputs) {
    lines.push(output.createTable);
    lines.push("");
    for (const idx of output.indexes) {
      lines.push(idx);
    }
    lines.push("");
  }

  return lines.join("\n");
}
