import { CodeBuilder } from "./code-builder";
import { pascalCase } from "../../utils/string-utils";

export interface EngineFactoryInput {
  entityNames: string[];
  hasFileFields: boolean;
}

export function generateEngineFactoryFile(input: EngineFactoryInput): string {
  const b = new CodeBuilder();
  b.line("// AUTO-GENERATED FILE - DO NOT EDIT");
  b.line("// Generated by drizzle-sync from backend schema");
  b.line("// Factory function to create a pre-configured SyncClientEngine for this app");
  b.blank();

  b.line('import { createSyncClientEngine } from "@avileo/drizzle-sync/client";');
  b.line('import { buildPendingDataFromRegistry } from "@avileo/drizzle-sync/pglite";');
  b.line('import type { SyncClientEngine, ISyncClientHttpClient } from "@avileo/drizzle-sync/client";');
  b.line('import { SCHEMA_SQL } from "./schema-sql";');
  b.line('import { SYNC_TABLE_REGISTRY } from "./sync-tables";');
  b.line('import { applierConfig } from "./applier";');
  if (input.hasFileFields) {
    b.line('import { FILE_FIELDS_CONFIG } from "./file-fields";');
  }
  b.line('import * as schema from "./schema";');
  b.blank();

  // Import generated services
  for (const name of input.entityNames) {
    const pascal = pascalCase(name);
    b.line(`import { ${pascal}Service } from "./services";`);
  }
  b.blank();

  // Generate AvileoGeneratedServices interface
  b.line("export interface AvileoGeneratedServices {");
  b.indent((ib) => {
    for (const name of input.entityNames) {
      const pascal = pascalCase(name);
      ib.line(`${name}: ${pascal}Service;`);
    }
  });
  b.line("}");
  b.blank();

  // Generate utility types
  b.line("export type AvileoServices<TOverrides extends Partial<AvileoGeneratedServices> = {}> = Omit<AvileoGeneratedServices, keyof TOverrides> & TOverrides;");
  b.blank();

  b.line("export type AvileoSyncEngine<TOverrides extends Partial<AvileoGeneratedServices> = {}> = SyncClientEngine<AvileoServices<TOverrides>>;");
  b.blank();

  // Generate service override factory type
  b.line("export type ServiceOverrides<TOverrides extends Partial<AvileoGeneratedServices>> = {");
  b.indent((ib) => {
    ib.line("[K in keyof TOverrides]: (engine: AvileoSyncEngine<TOverrides>) => TOverrides[K];");
  });
  b.line("};");
  b.blank();

  // Generate CreateEngineParams
  b.line("export interface CreateEngineParams<TOverrides extends Partial<AvileoGeneratedServices> = {}> {");
  b.indent((ib) => {
    ib.line("tenantId: string;");
    ib.line("userId: string;");
    ib.line("authToken: string;");
    ib.line("apiUrl: string;");
    ib.line("httpClient: ISyncClientHttpClient;");
    ib.line("dataDir?: string;");
    ib.line("versionKey?: string;");
    ib.line("/**");
    ib.line(" * App-level service overrides. Each key replaces the generated service");
    ib.line(" * with a custom implementation.");
    ib.line(" */");
    ib.line("serviceOverrides?: ServiceOverrides<TOverrides>;");
  });
  b.line("}");
  b.blank();

  // Helper function to build entity definitions with overrides
  b.line("function buildEntityDefinitions<TOverrides extends Partial<AvileoGeneratedServices>>(");
  b.indent((ib) => {
    ib.line("overrides?: ServiceOverrides<TOverrides>,");
  });
  b.line("): Array<{ name: string; entityType: string; factory: (engine: SyncClientEngine) => unknown }> {");
  b.indent((ib) => {
    ib.line("const definitions = [];");
    b.blank();

    for (const name of input.entityNames) {
      const pascal = pascalCase(name);
      ib.line(`const ${name}Factory = overrides?.${name};`);
      ib.line(`if (${name}Factory) {`);
      ib.indent((iib) => {
        ib.line(`definitions.push({ name: "${name}", entityType: "${name}", factory: (engine: SyncClientEngine) => ${name}Factory(engine as AvileoSyncEngine<TOverrides>) });`);
      });
      ib.line("} else {");
      ib.indent((iib) => {
        ib.line(`definitions.push({ name: "${name}", entityType: "${name}", factory: (engine: SyncClientEngine) => new ${pascal}Service(engine) });`);
      });
      ib.line("}");
    }

    b.blank();
    ib.line("return definitions;");
  });
  b.line("}");
  b.blank();

  // Generate createAvileoSyncEngine function
  b.line("export function createAvileoSyncEngine<TOverrides extends Partial<AvileoGeneratedServices> = {}>(");
  b.indent((ib) => {
    ib.line("params: CreateEngineParams<TOverrides>,");
  });
  b.line("): AvileoSyncEngine<TOverrides> {");
  b.indent((ib) => {
    ib.line("return createSyncClientEngine({");
    ib.indent((iib) => {
      iib.line("databaseConfig: {");
      iib.indent((iiib) => {
        iiib.line("dataDir: params.dataDir ?? 'idb://avileo',");
        iiib.line("schemaSql: SCHEMA_SQL,");
        iiib.line("drizzleSchema: schema,");
        iiib.line("pendingDataConfig: buildPendingDataFromRegistry(SYNC_TABLE_REGISTRY),");
      });
      iib.line("},");
      iib.line("tenantId: params.tenantId,");
      iib.line("tenantColumn: 'business_id',");
      iib.line("userId: params.userId,");
      iib.line("authToken: params.authToken,");
      iib.line("apiUrl: params.apiUrl,");
      iib.line("httpClient: params.httpClient,");
      iib.line("applierConfig,");
      if (input.hasFileFields) {
        iib.line("metadata: {");
        iib.indent((iiib) => {
          iiib.line("fileFields: FILE_FIELDS_CONFIG,");
        });
        iib.line("},");
      }
      iib.line("tables: schema,");
      iib.line("entities: buildEntityDefinitions(params.serviceOverrides),");
    });
    ib.line("}) as AvileoSyncEngine<TOverrides>;");
  });
  b.line("}");
  b.blank();

  b.line("export default createAvileoSyncEngine;");

  return b.toString();
}
