import { CodeBuilder } from "./code-builder";
import { pascalCase } from "../../utils/string-utils";

export interface EngineFactoryInput {
  entityNames: string[];
  hasFileFields: boolean;
}

export function generateEngineFactoryFile(input: EngineFactoryInput): string {
  const b = new CodeBuilder();
  b.line("// AUTO-GENERATED FILE - DO NOT EDIT");
  b.line("// Generated by drizzle-sync from backend schema");
  b.line("// Factory function to create a pre-configured SyncClientEngine for this app");
  b.blank();

  b.line('import { createSyncClientEngine } from "@avileo/drizzle-sync/client";');
  b.line('import { buildPendingDataFromRegistry } from "@avileo/drizzle-sync/client";');
  b.line('import type { SyncClientEngine, ISyncClientHttpClient } from "@avileo/drizzle-sync/client";');
  b.line('import { SCHEMA_SQL } from "./schema-sql";');
  b.line('import { SYNC_TABLE_REGISTRY } from "./sync-tables";');
  b.line('import { applierConfig } from "./applier";');
  if (input.hasFileFields) {
    b.line('import { FILE_FIELDS_CONFIG } from "./file-fields";');
  }
  b.line('import * as schema from "./schema";');
  b.blank();

  // Import generated services
  for (const name of input.entityNames) {
    const pascal = pascalCase(name);
    b.line(`import { ${pascal}Service } from "./services";`);
  }
  b.blank();

  b.line("export interface CreateEngineParams {");
  b.indent((ib) => {
    ib.line("tenantId: string;");
    ib.line("userId: string;");
    ib.line("authToken: string;");
    ib.line("apiUrl: string;");
    ib.line("httpClient: ISyncClientHttpClient;");
    ib.line("dataDir?: string;");
    ib.line("versionKey?: string;");
  });
  b.line("}");
  b.blank();

  b.line("export function createAvileoSyncEngine(params: CreateEngineParams): SyncClientEngine {");
  b.indent((ib) => {
    ib.line("return createSyncClientEngine({");
    ib.indent((iib) => {
      iib.line("databaseConfig: {");
      iib.indent((iiib) => {
        iiib.line("dataDir: params.dataDir ?? 'idb://avileo',");
        iiib.line("schemaSql: SCHEMA_SQL,");
        iiib.line("drizzleSchema: schema,");
        iiib.line("pendingDataConfig: buildPendingDataFromRegistry(SYNC_TABLE_REGISTRY),");
      });
      iib.line("},");
      iib.line("tenantId: params.tenantId,");
      iib.line("tenantColumn: 'business_id',");
      iib.line("userId: params.userId,");
      iib.line("authToken: params.authToken,");
      iib.line("apiUrl: params.apiUrl,");
      iib.line("httpClient: params.httpClient,");
      iib.line("applierConfig,");
      if (input.hasFileFields) {
        iib.line("metadata: {");
        iib.indent((iiib) => {
          iiib.line("fileFields: FILE_FIELDS_CONFIG,");
        });
        iib.line("},");
      }
      iib.line("tables: schema,");
      iib.line("entities: [");
      iib.indent((iiib) => {
        for (const name of input.entityNames) {
          const pascal = pascalCase(name);
          iiib.line(`{ name: "${name}", entityType: "${name}", factory: (engine) => new ${pascal}Service(engine) },`);
        }
      });
      iib.line("],");
    });
    ib.line("});");
  });
  b.line("}");
  b.blank();

  b.line("export default createAvileoSyncEngine;");

  return b.toString();
}
