import { camelCase } from "../../utils/string-utils";
import { CodeBuilder } from "./code-builder";
import type { EntitySyncConfig } from "../types";
import type { SerializedEntity } from "../schema-types";

type FileFieldEntity = EntitySyncConfig | SerializedEntity;

function isSerializedEntity(entity: FileFieldEntity): entity is SerializedEntity {
  return "columns" in entity && "config" in entity;
}

function getFileFields(
  entity: FileFieldEntity
): Record<string, { entity: "files" | "assets"; maxSize?: number; accept?: string[] }> | undefined {
  if (isSerializedEntity(entity)) {
    return entity.config.fileFields;
  }
  return entity.fileFields;
}

export interface FileFieldEntry {
  entityName: string;
  fields: Record<string, { entity: string; maxSize?: number; accept?: string[] }>;
}

export function generateFileFieldsConfig(
  entityName: string,
  entity: FileFieldEntity
): FileFieldEntry | null {
  const fileFields = getFileFields(entity);
  if (!fileFields || Object.keys(fileFields).length === 0) return null;

  const fields: Record<string, { entity: string; maxSize?: number; accept?: string[] }> = {};
  for (const [fieldName, config] of Object.entries(fileFields)) {
    fields[camelCase(fieldName)] = {
      entity: config.entity,
      ...(config.maxSize ? { maxSize: config.maxSize } : {}),
      ...(config.accept ? { accept: config.accept } : {}),
    };
  }

  return { entityName, fields };
}

export function generateFileFieldsFile(entries: FileFieldEntry[]): string {
  const b = new CodeBuilder();
  b.line("// AUTO-GENERATED FILE - DO NOT EDIT");
  b.line("// Generated by drizzle-sync from backend schema");
  b.blank();

  if (entries.length === 0) {
    b.line("export const FILE_FIELDS_CONFIG = {} as const;");
    b.blank();
    b.line("export interface FileFieldConfig { entity: string; maxSize?: number; accept?: string[] }");
    b.line("export function getFileFieldConfig(_entity: string, _field: string): FileFieldConfig | undefined { return undefined; }");
    return b.toString();
  }

  b.line("export const FILE_FIELDS_CONFIG = {");
  b.indent((ib) => {
    for (const entry of entries) {
      ib.line(`"${entry.entityName}": {`);
      ib.indent((iib) => {
        for (const [fieldName, config] of Object.entries(entry.fields)) {
          const parts = [`entity: "${config.entity}"`];
          if (config.maxSize !== undefined) parts.push(`maxSize: ${config.maxSize}`);
          if (config.accept) {
            const items = config.accept.map((a) => `"${a}"`).join(", ");
            parts.push(`accept: [${items}] as const`);
          }
          iib.line(`"${fieldName}": { ${parts.join(", ")} },`);
        }
      });
      ib.line("},");
    }
  });
  b.line("} as const;");
  b.blank();

  b.line("export interface FileFieldConfig {");
  b.indent((ib) => {
    ib.line("entity: \"files\" | \"assets\";");
    ib.line("maxSize?: number;");
    ib.line("accept?: readonly string[];");
  });
  b.line("}");
  b.blank();

  b.line("export type FileFieldsEntityMap = typeof FILE_FIELDS_CONFIG;");
  b.line("export type FileFieldsEntity = keyof FileFieldsEntityMap;");
  b.blank();

  b.line("export function getFileFieldConfig(");
  b.indent((ib) => {
    ib.line("entityName: string,");
    ib.line("fieldName: string");
  });
  b.line("): FileFieldConfig | undefined {");
  b.indent((ib) => {
    ib.line("const entity = (FILE_FIELDS_CONFIG as Record<string, Record<string, FileFieldConfig>>)[entityName];");
    ib.line("if (!entity) return undefined;");
    ib.line("return entity[fieldName];");
  });
  b.line("}");
  b.blank();

  b.line("export function isFileField(entityName: string, fieldName: string): boolean {");
  b.indent((ib) => {
    ib.line("return getFileFieldConfig(entityName, fieldName) !== undefined;");
  });
  b.line("}");

  return b.toString();
}
