import { CodeBuilder } from "./code-builder";

export function generateQueryKeysFile(entityNames: string[]): string {
  const b = new CodeBuilder();
  b.line("// AUTO-GENERATED FILE - DO NOT EDIT");
  b.line("// Generated by drizzle-sync from backend schema");
  b.line("// Maps sync entity types to TanStack Query key arrays for cache invalidation");
  b.blank();

  b.line("export const SYNC_TO_QUERY_KEYS: Record<string, string[][]> = {");
  b.indent((ib) => {
    for (const name of entityNames) {
      const pascal = name.charAt(0).toUpperCase() + name.slice(1);
      ib.line(`${name}: [[`);
      ib.indent((iib) => {
        iib.line(`["${name}-new"],`);
        iib.line(`["${name}-new", "list"],`);
      });
      ib.line(`]],`);
    }
  });
  b.line("};");
  b.blank();

  b.line("export function getQueryKeysForEntity(entityType: string): string[][] {");
  b.indent((ib) => {
    ib.line("return SYNC_TO_QUERY_KEYS[entityType] ?? [];");
  });
  b.line("}");
  b.blank();

  b.line("export default getQueryKeysForEntity;");

  return b.toString();
}
