import { CodeBuilder } from "./code-builder";

export function generateSchemaSQLFile(ddlContent: string): string {
  const b = new CodeBuilder();
  b.line("// AUTO-GENERATED FILE - DO NOT EDIT");
  b.line("// Generated by drizzle-sync from backend schema");
  b.line("// PostgreSQL-compatible DDL for PGlite as TypeScript string");
  b.blank();
  b.line("export const SCHEMA_SQL = `");
  b.line(ddlContent);
  b.line("`;");
  b.blank();
  b.line("export default SCHEMA_SQL;");

  return b.toString();
}
