import { CodeBuilder } from "./code-builder";
import { pascalCase } from "../../utils/string-utils";
import type { SerializedEntity } from "../schema-types";

export interface ServerFactoryInput {
  entityNames: string[];
  entities: Record<string, SerializedEntity>;
  tenancyColumn: string;
}

export interface GeneratedEntityResolver {
  entityName: string;
  pascalName: string;
  tableName: string;
  idField: string;
  versionField: string;
  tenantColumn: string;
  hasRelations: boolean;
  parentRelations: Array<{ entity: string; foreignKey: string }>;
  childRelations: Array<{ entity: string; foreignKey: string }>;
}

function generateEntityResolver(input: {
  entity: SerializedEntity;
  tenantColumn: string;
}): GeneratedEntityResolver {
  const { entity, tenantColumn } = input;
  const pascalName = pascalCase(entity.name);

  const idField = entity.columns.find((c) => c.primary)?.name ?? "id";
  const versionField = entity.columns.find((c) => c.name === "version")?.name ?? "version";

  const parentRelations = entity.config.relations?.parents ?? [];
  const childRelations = entity.config.relations?.children ?? [];

  return {
    entityName: entity.name,
    pascalName,
    tableName: entity.tableName,
    idField,
    versionField,
    tenantColumn,
    hasRelations: parentRelations.length > 0 || childRelations.length > 0,
    parentRelations,
    childRelations,
  };
}

export function generateServerFactoryFile(input: ServerFactoryInput): string {
  const b = new CodeBuilder();
  b.line("// AUTO-GENERATED FILE - DO NOT EDIT");
  b.line("// Generated by drizzle-sync from backend schema");
  b.line("// Factory for creating pre-configured SyncService for this app");
  b.blank();

  b.line("import { NodePgDatabase } from \"drizzle-orm/node-postgres\";");
  b.line("import type { PgTable } from \"drizzle-orm/pg-core\";");
  b.line('import * as schema from "../schema";');
  b.blank();

  b.line("import {");
  b.indent((ib) => {
    ib.line("SyncService,");
    ib.line("type SyncServiceConfig,");
    ib.line("type SyncServiceHooks,");
  });
  b.line('} from "@avileo/drizzle-sync/server";');
  b.blank();
  b.line("import {");
  b.indent((ib) => {
    ib.line("DrizzleSyncOperationRepository,");
    ib.line("DrizzleSyncConflictRepository,");
    ib.line("DrizzleSyncDeadLetterRepository,");
  });
  b.line('} from "@avileo/drizzle-sync/server";');
  b.blank();
  b.line("import {");
  b.indent((ib) => {
    ib.line("SyncEngine,");
    ib.line("GenericConflictResolverRegistry,");
    ib.line("createSyncLoggerAdapter,");
    ib.line("GenericHandlerRegistry,");
  });
  b.line('} from "@avileo/drizzle-sync/server";');
  b.blank();
  b.line("import {");
  b.indent((ib) => {
    ib.line("GenericSyncHandler,");
    ib.line("type GenericRepo,");
  });
  b.line('} from "@avileo/drizzle-sync/server";');
  b.blank();

  b.line("import {");
  b.indent((ib) => {
    ib.line("syncOperationsTable,");
    ib.line("syncConflictsTable,");
    ib.line("syncDeadLetterTable,");
  });
  b.line("} from \"../schema\";");
  b.blank();

  b.line("import type { SyncRequestContext } from \"@avileo/drizzle-sync/server\";");
  b.line("import type { ISyncEventEmitter } from \"@avileo/drizzle-sync/core\";");
  b.blank();

  for (const name of input.entityNames) {
    b.line(`import { ${pascalCase(name)}Repo } from "../repos";`);
  }
  b.blank();

  b.line("// ============================================================================");
  b.line("// Sync Service Factory");
  b.line("// ============================================================================");
  b.blank();

  b.line("export interface AvileoSyncFactoryOptions {");
  b.indent((ib) => {
    ib.line("/** Database client */");
    ib.line("db: NodePgDatabase<typeof schema>;");
    ib.line("/** Optional logger adapter */");
    ib.line("logger?: ReturnType<typeof createSyncLoggerAdapter>;");
    ib.line("/** Optional metrics collector */");
    ib.line("metricsCollector?: { getMetrics(ctx: SyncRequestContext, hours?: number): Promise<unknown> };");
    ib.line("/** Optional event emitter */");
    ib.line("eventEmitter?: ISyncEventEmitter;");
    ib.line("/** Tenant column name (default: business_id) */");
    ib.line("tenantColumn?: string;");
  });
  b.line("}");
  b.blank();

  b.line("export interface EntityHandlerConfig {");
  b.indent((ib) => {
    ib.line("/** Custom handler factory function */");
    ib.line("handler: (deps: { db: NodePgDatabase<typeof schema>; repo: GenericRepo }) => GenericSyncHandler<any, any, string>;");
    ib.line("/** Custom repository (optional - will use generated repo if not provided) */");
    ib.line("repo?: GenericRepo;");
  });
  b.line("}");
  b.blank();

  b.line("export class AvileoSyncFactory {");
  b.indent((ib) => {
    ib.line("private readonly options: Required<AvileoSyncFactoryOptions>;");
    ib.line("private readonly hooks: SyncServiceHooks<SyncRequestContext> = {};");
    ib.line("private readonly customHandlers = new Map<string, EntityHandlerConfig>();");
    ib.line("private readonly customResolvers = new Map<string, any>();");
    b.blank();

    ib.line("constructor(options: AvileoSyncFactoryOptions) {");
    ib.indent((iib) => {
      iib.line("this.options = {");
      iib.indent((iiib) => {
        iiib.line("db: options.db,");
        iiib.line("logger: options.logger ?? createSyncLoggerAdapter(),");
        iiib.line("metricsCollector: options.metricsCollector,");
        iiib.line("eventEmitter: options.eventEmitter,");
        iiib.line("tenantColumn: options.tenantColumn ?? \"business_id\",");
      });
      iib.line("};");
    });
    ib.line("}");
    b.blank();

    ib.line("/**");
    ib.line(" * Register a hook for when conflicts are detected");
    ib.line(" */");
    ib.line("onConflictDetected(");
    b.indent((iib) => {
      iib.line("handler: NonNullable<SyncServiceHooks<SyncRequestContext>[\"onConflictDetected\"]>");
    });
    ib.line("): this {");
    b.indent((iib) => {
      iib.line("this.hooks.onConflictDetected = handler;");
      iib.line("return this;");
    });
    ib.line("}");
    b.blank();

    ib.line("/**");
    ib.line(" * Register a hook for enriching changes before returning to client");
    ib.line(" */");
    ib.line("enrichChanges(");
    b.indent((iib) => {
      iib.line("handler: NonNullable<SyncServiceHooks<SyncRequestContext>[\"enrichChanges\"]>");
    });
    ib.line("): this {");
    b.indent((iib) => {
      iib.line("this.hooks.enrichChanges = handler;");
      iib.line("return this;");
    });
    ib.line("}");
    b.blank();

    ib.line("/**");
    ib.line(" * Register a hook called before each operation is processed");
    ib.line(" */");
    ib.line("beforeOperation(");
    b.indent((iib) => {
      iib.line("handler: NonNullable<SyncServiceHooks<SyncRequestContext>[\"beforeOperation\"]>");
    });
    ib.line("): this {");
    b.indent((iib) => {
      iib.line("this.hooks.beforeOperation = handler;");
      iib.line("return this;");
    });
    ib.line("}");
    b.blank();

    ib.line("/**");
    ib.line(" * Register a hook called after each operation is processed");
    ib.line(" */");
    ib.line("afterOperation(");
    b.indent((iib) => {
      iib.line("handler: NonNullable<SyncServiceHooks<SyncRequestContext>[\"afterOperation\"]>");
    });
    ib.line("): this {");
    b.indent((iib) => {
      iib.line("this.hooks.afterOperation = handler;");
      iib.line("return this;");
    });
    ib.line("}");
    b.blank();

    ib.line("/**");
    ib.line(" * Register a hook called after a batch is completed");
    ib.line(" */");
    ib.line("onBatchComplete(");
    b.indent((iib) => {
      iib.line("handler: NonNullable<SyncServiceHooks<SyncRequestContext>[\"onBatchComplete\"]>");
    });
    ib.line("): this {");
    b.indent((iib) => {
      iib.line("this.hooks.onBatchComplete = handler;");
      iib.line("return this;");
    });
    ib.line("}");
    b.blank();

    ib.line("/**");
    ib.line(" * Register a custom handler for an entity");
    ib.line(" */");
    ib.line("withHandler(entity: string, config: EntityHandlerConfig): this {");
    b.indent((iib) => {
      iib.line("this.customHandlers.set(entity, config);");
      iib.line("return this;");
    });
    ib.line("}");
    b.blank();

    ib.line("/**");
    ib.line(" * Register a custom conflict resolver for an entity");
    ib.line(" */");
    ib.line("withConflictResolver(entity: string, resolver: any): this {");
    b.indent((iib) => {
      iib.line("this.customResolvers.set(entity, resolver);");
      iib.line("return this;");
    });
    ib.line("}");
    b.blank();

    ib.line("/**");
    ib.line(" * Build the SyncService instance");
    ib.line(" */");
    ib.line("build(): SyncService<SyncRequestContext> {");
    b.indent((iib) => {
      iib.line("// Create Drizzle repositories");
      iib.line("const operationRepo = new DrizzleSyncOperationRepository({");
      iib.indent((iiib) => {
        iiib.line("table: syncOperationsTable as any,");
        iiib.line("tenantColumn: this.options.tenantColumn,");
        iiib.line("db: this.options.db,");
      });
      iib.line("});");
      b.blank();

      iib.line("const conflictRepo = new DrizzleSyncConflictRepository({");
      iib.indent((iiib) => {
        iiib.line("table: syncConflictsTable as any,");
        iiib.line("tenantColumn: this.options.tenantColumn,");
        iiib.line("db: this.options.db,");
      });
      iib.line("});");
      b.blank();

      iib.line("const deadLetterRepo = new DrizzleSyncDeadLetterRepository({");
      iib.indent((iiib) => {
        iiib.line("table: syncDeadLetterTable as any,");
        iiib.line("tenantColumn: this.options.tenantColumn,");
        iiib.line("db: this.options.db,");
      });
      iib.line("});");
      b.blank();

      iib.line("// Create conflict resolver registry");
      iib.line("const conflictRegistry = new GenericConflictResolverRegistry<string, SyncRequestContext, unknown>();");
      b.blank();

      iib.line("// Register custom conflict resolvers");
      iib.line("for (const [entity, resolver] of this.customResolvers) {");
      iib.indent((iiib) => {
        iiib.line("conflictRegistry.register(entity, resolver);");
      });
      iib.line("}");
      b.blank();

      iib.line("// Create sync engine with handler registry");
      iib.line("const handlerDeps = { db: this.options.db };");
      iib.line("const handlerRegistry = new GenericHandlerRegistry<string, typeof handlerDeps>(handlerDeps);");
      b.blank();

      iib.line("// Register custom handlers");
      iib.line("for (const [entity, config] of this.customHandlers) {");
      iib.indent((iiib) => {
        iiib.line("const repo = config.repo ?? this.createDefaultRepo(entity);");
        iiib.line(`handlerRegistry.register(entity, () => config.handler({ db: this.options.db, repo }));`);
      });
      iib.line("}");
      b.blank();

      iib.line("// Create sync engine");
      iib.line("const engine = new SyncEngine({");
      iib.indent((iiib) => {
        iiib.line("handlerDeps,");
        iiib.line("handlerRegistry: handlerRegistry as any,");
      });
      iib.line("}, {");
      iib.indent((iiib) => {
        iiib.line("db: this.options.db as any,");
        iiib.line("syncOpRepo: operationRepo as any,");
        iiib.line("syncConflictRepo: conflictRepo as any,");
        iiib.line("conflictResolverRegistry: conflictRegistry as any,");
        iiib.line("logger: this.options.logger,");
        iiib.line("eventEmitter: this.options.eventEmitter,");
        iiib.line("now: () => new Date().toISOString(),");
        iiib.line("savepointSql: (name) => `SAVEPOINT ${name}`,");
        iiib.line("releaseSavepointSql: (name) => `RELEASE SAVEPOINT ${name}`,");
        iiib.line("rollbackSavepointSql: (name) => `ROLLBACK TO SAVEPOINT ${name}`,");
      });
      iib.line("});");
      b.blank();

      iib.line("// Create and return SyncService");
      iib.line("const serviceConfig: SyncServiceConfig<SyncRequestContext> = {");
      iib.indent((iiib) => {
        iiib.line("engine: engine as any,");
        iiib.line("syncOpRepo: operationRepo as any,");
        iiib.line("syncConflictRepo: conflictRepo as any,");
        iiib.line("syncDeadLetterRepo: deadLetterRepo as any,");
        iiib.line("conflictResolverRegistry: conflictRegistry as any,");
        iiib.line("hooks: this.hooks,");
        iiib.line("metricsCollector: this.options.metricsCollector,");
        iiib.line("eventEmitter: this.options.eventEmitter,");
        iiib.line("now: () => new Date().toISOString(),");
      });
      iib.line("};");
      b.blank();

      iib.line("return new SyncService(serviceConfig);");
    });
    ib.line("}");
    b.blank();

    ib.line("/**");
    ib.line(" * Create default repository for an entity");
    ib.line(" */");
    ib.line("private createDefaultRepo(entity: string): GenericRepo {");
    b.indent((iib) => {
      iib.line("return {");
      iib.indent((iiib) => {
        iiib.line("create: async (ctx, data) => { throw new Error(`No repo for ${entity}`); },");
        iiib.line("findById: async (ctx, id) => { throw new Error(`No repo for ${entity}`); },");
        iiib.line("update: async (ctx, id, data) => { throw new Error(`No repo for ${entity}`); },");
        iiib.line("delete: async (ctx, id) => { throw new Error(`No repo for ${entity}`); },");
      });
      iib.line("};");
    });
    ib.line("}");
  });
  b.line("}");
  b.blank();

  b.line("export default AvileoSyncFactory;");

  return b.toString();
}

export function generateServerIndexFile(input: ServerFactoryInput): string {
  const b = new CodeBuilder();
  b.line("// AUTO-GENERATED FILE - DO NOT EDIT");
  b.line("// Generated by drizzle-sync from backend schema");
  b.blank();

  b.line("export { AvileoSyncFactory } from \"./sync-factory\";");
  b.line("export type { AvileoSyncFactoryOptions, EntityHandlerConfig } from \"./sync-factory\";");
  b.blank();

  b.line("// Re-export schema for convenience");
  b.line("export { schema } from \"./schema\";");

  return b.toString();
}