import type { EntitySyncConfig } from "../../config/types";
import type { SerializedEntity } from "../../config/schema-types";
import { CodeBuilder } from "./code-builder";

type GenerationInput = EntitySyncConfig | SerializedEntity;

function isSerializedEntity(entity: GenerationInput): entity is SerializedEntity {
  return "tableName" in entity && "columns" in entity;
}

export interface SyncTableEntry {
  name: string;
  entityType: string;
  dependsOn: string[];
}

export function generateTableRegistry(
  entityNames: string[],
  entities: Record<string, GenerationInput>
): SyncTableEntry[] {
  return entityNames.map((name) => {
    const entity = entities[name];
    let dependsOn: string[] = [];
    let tableName = name;

    if (isSerializedEntity(entity)) {
      dependsOn = entity.graph.parents || [];
      tableName = entity.tableName;
    } else {
      const config = entity as EntitySyncConfig;
      if (config.relations?.parents) {
        dependsOn = config.relations.parents.map((p) => p.entity);
      }
    }

    return {
      name: tableName,
      entityType: name,
      dependsOn,
    };
  });
}

export function generateTableRegistryFile(entries: SyncTableEntry[]): string {
  const b = new CodeBuilder();
  b.line("// AUTO-GENERATED FILE - DO NOT EDIT");
  b.line("// Generated by drizzle-sync from backend schema");
  b.line("// Registry of syncable tables with dependencies for pending data export/import");
  b.blank();

  b.line("export interface SyncTableEntry {");
  b.indent((ib) => {
    ib.line("name: string;");
    ib.line("entityType: string;");
    ib.line("dependsOn: string[];");
  });
  b.line("}");
  b.blank();

  b.line("export const SYNC_TABLE_REGISTRY: SyncTableEntry[] = [");
  b.indent((ib) => {
    for (const entry of entries) {
      if (entry.dependsOn.length > 0) {
        ib.line(`{ name: "${entry.name}", entityType: "${entry.entityType}", dependsOn: [${entry.dependsOn.map((d) => `"${d}"`).join(", ")}] },`);
      } else {
        ib.line(`{ name: "${entry.name}", entityType: "${entry.entityType}", dependsOn: [] },`);
      }
    }
  });
  b.line("];");
  b.blank();

  b.line("export default SYNC_TABLE_REGISTRY;");

  return b.toString();
}
