import { camelCase, pascalCase } from "../../utils/string-utils";
import type { ColumnMetadata } from "../../config/types";
import type { FieldCodec } from "../../codecs/types";
import type { SerializedEntity } from "../../config/schema-types";
import { getColumnsToInclude, getGeneratorConfig, type GeneratorEntity } from "./schema-adapter";

export interface ZodSchemaOutput {
  name: string;
  schemaCode: string;
  typeCode: string;
  interfaceCode: string;
}

export function generateZodSchema(
  entityName: string,
  entity: GeneratorEntity
): ZodSchemaOutput {
  const columnsToInclude = getColumnsToInclude(entity);
  const config = getGeneratorConfig(entity);

  const fields: string[] = [];

  for (const col of columnsToInclude) {
    const zodCode = columnToZod(col, config.fieldCodecs?.[col.name]);
    fields.push(`  ${camelCase(col.name)}: ${zodCode},`);
  }

  if (!columnsToInclude.find((c) => c.name === "sync_status")) {
    fields.push(`  syncStatus: z.enum(["pending", "synced", "error"]).default("pending"),`);
  }

  if (!columnsToInclude.find((c) => c.name === "sync_attempts")) {
    fields.push(`  syncAttempts: z.number().default(0),`);
  }

  const schemaCode = `export const ${entityName}Schema = z.object({\n${fields.join("\n")}\n});`;

  const typeName = pascalCase(entityName);
  const typeCode = `export type ${typeName} = z.infer<typeof ${entityName}Schema>;`;

  const interfaceFields = columnsToInclude
    .map((col) => {
      const type = getTypeScriptType(col, config.fieldCodecs?.[col.name]);
      return `  ${camelCase(col.name)}${col.notNull ? "" : "?"}: ${type};`;
    })
    .join("\n");

  const interfaceCode = `export interface ${typeName}Input {\n${interfaceFields}\n}`;

  return {
    name: `${entityName}Schema`,
    schemaCode,
    typeCode,
    interfaceCode,
  };
}

function columnToZod(col: ColumnMetadata, codec?: FieldCodec): string {
  if (codec) {
    const codecZod = codecToZod(codec);
    if (codecZod) {
      return col.notNull ? codecZod : `${codecZod}.nullable()`;
    }
  }

  let base: string;

  switch (col.dataType) {
    case "string":
      base = "z.string()";
      break;
    case "number":
      base = "z.number()";
      break;
    case "boolean":
      base = "z.boolean()";
      break;
    case "date":
      base = "z.coerce.date()";
      break;
    case "enum":
      if (col.enumValues && col.enumValues.length > 0) {
        const values = col.enumValues.map((v) => `"${v}"`).join(", ");
        base = `z.enum([${values}])`;
      } else {
        base = "z.string()";
      }
      break;
    case "json":
      base = "z.record(z.string(), z.unknown())";
      break;
    default:
      base = "z.unknown()";
  }

  if (!col.notNull) {
    base += ".nullable()";
  }

  return base;
}

function codecToZod(codec: FieldCodec): string | null {
  switch (codec.kind) {
    case "currency":
    case "weight":
    case "decimal":
      return "z.union([z.string(), z.number()])";
    case "empty-string-to-null":
      return "z.string()";
    case "date-only":
      return "z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/)";
    default:
      return null;
  }
}

function getTypeScriptType(col: ColumnMetadata, codec?: FieldCodec): string {
  if (codec) {
    const codecType = codecToTypeScript(codec);
    if (codecType) {
      return codecType;
    }
  }

  switch (col.dataType) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "date":
      return "Date";
    case "enum":
      return col.enumValues?.map((v) => `"${v}"`).join(" | ") || "string";
    case "json":
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

function codecToTypeScript(codec: FieldCodec): string | null {
  switch (codec.kind) {
    case "currency":
    case "weight":
    case "decimal":
      return "string | number";
    case "empty-string-to-null":
      return "string";
    case "date-only":
      return "string";
    default:
      return null;
  }
}

export function generateZodSchemasFile(schemas: ZodSchemaOutput[]): string {
  const warning = `// AUTO-GENERATED FILE - DO NOT EDIT\n// Generated by drizzle-sync from backend schema\n\n`;

  const imports = `import { z } from "zod";\n\n`;

  const content = schemas.map((s) => `${s.schemaCode}\n\n${s.typeCode}\n\n${s.interfaceCode}`).join("\n\n");

  return warning + imports + content;
}

export function generateZodSchemaFromSerialized(
  entityName: string,
  entity: SerializedEntity
): ZodSchemaOutput {
  return generateZodSchema(entityName, entity);
}
