import { camelCase, pascalCase } from "../../utils/string-utils";
import type { ColumnMetadata, EntitySyncConfig } from "../../config/types";
import { introspectTable, resolveColumns } from "../../config/introspect";

export interface ZodSchemaOutput {
  name: string;
  schemaCode: string;
  typeCode: string;
  interfaceCode: string;
}

export function generateZodSchema(
  entityName: string,
  config: EntitySyncConfig
): ZodSchemaOutput {
  const columns = introspectTable(config.table);
  const columnsToInclude = resolveColumns(columns, config);

  const fields: string[] = [];

  for (const col of columnsToInclude) {
    const zodCode = columnToZod(col);
    fields.push(`  ${camelCase(col.name)}: ${zodCode},`);
  }

  if (!columnsToInclude.find((c) => c.name === "sync_status")) {
    fields.push(`  syncStatus: z.enum(["pending", "synced", "error"]).default("pending"),`);
  }

  if (!columnsToInclude.find((c) => c.name === "sync_attempts")) {
    fields.push(`  syncAttempts: z.number().default(0),`);
  }

  const schemaCode = `export const ${entityName}Schema = z.object({\n${fields.join("\n")}\n});`;

  const typeName = pascalCase(entityName);
  const typeCode = `export type ${typeName} = z.infer<typeof ${entityName}Schema>;`;

  const interfaceFields = columnsToInclude
    .map((col) => {
      const type = getTypeScriptType(col);
      return `  ${camelCase(col.name)}${col.notNull ? "" : "?"}: ${type};`;
    })
    .join("\n");

  const interfaceCode = `export interface ${typeName}Input {\n${interfaceFields}\n}`;

  return {
    name: `${entityName}Schema`,
    schemaCode,
    typeCode,
    interfaceCode,
  };
}

function columnToZod(col: ColumnMetadata): string {
  let base: string;

  switch (col.dataType) {
    case "string":
      base = "z.string()";
      break;
    case "number":
      base = "z.number()";
      break;
    case "boolean":
      base = "z.boolean()";
      break;
    case "date":
      base = "z.coerce.date()";
      break;
    case "enum":
      if (col.enumValues && col.enumValues.length > 0) {
        const values = col.enumValues.map((v) => `"${v}"`).join(", ");
        base = `z.enum([${values}])`;
      } else {
        base = "z.string()";
      }
      break;
    case "json":
      base = "z.record(z.unknown())";
      break;
    default:
      base = "z.unknown()";
  }

  if (!col.notNull) {
    base += ".nullable()";
  }

  return base;
}

function getTypeScriptType(col: ColumnMetadata): string {
  switch (col.dataType) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "date":
      return "Date";
    case "enum":
      return col.enumValues?.map((v) => `"${v}"`).join(" | ") || "string";
    case "json":
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

export function generateZodSchemasFile(schemas: ZodSchemaOutput[]): string {
  const warning = `// AUTO-GENERATED FILE - DO NOT EDIT\n// Generated by drizzle-sync from backend schema\n\n`;

  const imports = `import { z } from "zod";\n\n`;

  const content = schemas.map((s) => `${s.schemaCode}\n\n${s.typeCode}\n\n${s.interfaceCode}`).join("\n\n");

  return warning + imports + content;
}
