// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/invitations/:token": {
    params: {
      "token": string;
    };
  };
  "/venta/:token": {
    params: {
      "token": string;
    };
  };
  "/reportes/cuentas-por-cobrar": {
    params: {};
  };
  "/reportes/compras-sugeridas": {
    params: {};
  };
  "/proveedores/:id": {
    params: {
      "id": string;
    };
  };
  "/proveedores/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/ayuda/:module/:slug": {
    params: {
      "module": string;
      "slug": string;
    };
  };
  "/clientes/:id": {
    params: {
      "id": string;
    };
  };
  "/proveedores": {
    params: {};
  };
  "/whatsapp/historial": {
    params: {};
  };
  "/clientes/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/proveedores/nuevo": {
    params: {};
  };
  "/ventas/:id": {
    params: {
      "id": string;
    };
  };
  "/ventas/:id/editar": {
    params: {
      "id": string;
    };
  };
  "/ventas/:id/editar/calculadora": {
    params: {
      "id": string;
    };
  };
  "/productos": {
    params: {};
  };
  "/business/create": {
    params: {};
  };
  "/clientes": {
    params: {};
  };
  "/mi-distribucion": {
    params: {};
  };
  "/productos/nuevo": {
    params: {};
  };
  "/clientes/nuevo": {
    params: {};
  };
  "/distribuciones": {
    params: {};
  };
  "/distribuciones/:id/editar": {
    params: {
      "id": string;
    };
  };
  "/distribuciones/nueva": {
    params: {};
  };
  "/business/edit": {
    params: {};
  };
  "/cobros": {
    params: {};
  };
  "/productos/:id": {
    params: {
      "id": string;
    };
  };
  "/ventas": {
    params: {};
  };
  "/ayuda": {
    params: {};
  };
  "/cobros/nuevo": {
    params: {};
  };
  "/invitations": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/activos": {
    params: {};
  };
  "/compras": {
    params: {};
  };
  "/compras/nueva": {
    params: {};
  };
  "/compras/nueva/:draftId?/calculadora": {
    params: {
      "draftId"?: string;
    };
  };
  "/compras/nueva/:draftId?": {
    params: {
      "draftId"?: string;
    };
  };
  "/compras/:id": {
    params: {
      "id": string;
    };
  };
  "/compras/:id/editar": {
    params: {
      "id": string;
    };
  };
  "/compras/:id/editar/calculadora": {
    params: {
      "id": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/visitas": {
    params: {};
  };
  "/cierre": {
    params: {};
  };
  "/config": {
    params: {};
  };
  "/config/payment-methods": {
    params: {};
  };
  "/config/notifications": {
    params: {};
  };
  "/config/puntos-venta": {
    params: {};
  };
  "/config/appearance": {
    params: {};
  };
  "/config/conflictos": {
    params: {};
  };
  "/config/security": {
    params: {};
  };
  "/config/whatsapp": {
    params: {};
  };
  "/config/whatsapp/templates": {
    params: {};
  };
  "/config/flags": {
    params: {};
  };
  "/config/tags": {
    params: {};
  };
  "/grupos": {
    params: {};
  };
  "/team": {
    params: {};
  };
  "/landing": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/sync": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/invitations/:token" | "/venta/:token" | "/reportes/cuentas-por-cobrar" | "/reportes/compras-sugeridas" | "/proveedores/:id" | "/proveedores/:id/edit" | "/ayuda/:module/:slug" | "/clientes/:id" | "/proveedores" | "/whatsapp/historial" | "/clientes/:id/edit" | "/proveedores/nuevo" | "/ventas/:id" | "/ventas/:id/editar" | "/ventas/:id/editar/calculadora" | "/productos" | "/business/create" | "/clientes" | "/mi-distribucion" | "/productos/nuevo" | "/clientes/nuevo" | "/distribuciones" | "/distribuciones/:id/editar" | "/distribuciones/nueva" | "/business/edit" | "/cobros" | "/productos/:id" | "/ventas" | "/ayuda" | "/cobros/nuevo" | "/invitations" | "/dashboard" | "/activos" | "/compras" | "/compras/nueva" | "/compras/nueva/:draftId?/calculadora" | "/compras/nueva/:draftId?" | "/compras/:id" | "/compras/:id/editar" | "/compras/:id/editar/calculadora" | "/profile" | "/visitas" | "/cierre" | "/config" | "/config/payment-methods" | "/config/notifications" | "/config/puntos-venta" | "/config/appearance" | "/config/conflictos" | "/config/security" | "/config/whatsapp" | "/config/whatsapp/templates" | "/config/flags" | "/config/tags" | "/grupos" | "/team" | "/landing" | "/login" | "/sync";
  };
  "routes/invitations.$token.tsx": {
    id: "routes/invitations.$token";
    page: "/invitations/:token";
  };
  "routes/venta.$token.tsx": {
    id: "routes/venta.$token";
    page: "/venta/:token";
  };
  "routes/_protected.tsx": {
    id: "routes/_protected";
    page: "/reportes/cuentas-por-cobrar" | "/reportes/compras-sugeridas" | "/proveedores/:id" | "/proveedores/:id/edit" | "/ayuda/:module/:slug" | "/clientes/:id" | "/proveedores" | "/whatsapp/historial" | "/clientes/:id/edit" | "/proveedores/nuevo" | "/ventas/:id" | "/ventas/:id/editar" | "/ventas/:id/editar/calculadora" | "/productos" | "/business/create" | "/clientes" | "/mi-distribucion" | "/productos/nuevo" | "/clientes/nuevo" | "/distribuciones" | "/distribuciones/:id/editar" | "/distribuciones/nueva" | "/business/edit" | "/cobros" | "/productos/:id" | "/ventas" | "/ayuda" | "/cobros/nuevo" | "/invitations" | "/dashboard" | "/activos" | "/compras" | "/compras/nueva" | "/compras/nueva/:draftId?/calculadora" | "/compras/nueva/:draftId?" | "/compras/:id" | "/compras/:id/editar" | "/compras/:id/editar/calculadora" | "/profile" | "/visitas" | "/cierre" | "/config" | "/config/payment-methods" | "/config/notifications" | "/config/puntos-venta" | "/config/appearance" | "/config/conflictos" | "/config/security" | "/config/whatsapp" | "/config/whatsapp/templates" | "/config/flags" | "/config/tags" | "/grupos" | "/team";
  };
  "routes/_protected.reportes.cuentas-por-cobrar.tsx": {
    id: "routes/_protected.reportes.cuentas-por-cobrar";
    page: "/reportes/cuentas-por-cobrar";
  };
  "routes/_protected.reportes.compras-sugeridas.tsx": {
    id: "routes/_protected.reportes.compras-sugeridas";
    page: "/reportes/compras-sugeridas";
  };
  "routes/_protected.proveedores.$id._index.tsx": {
    id: "routes/_protected.proveedores.$id._index";
    page: "/proveedores/:id";
  };
  "routes/_protected.proveedores.$id.edit.tsx": {
    id: "routes/_protected.proveedores.$id.edit";
    page: "/proveedores/:id/edit";
  };
  "routes/_protected.ayuda.$module.$slug.tsx": {
    id: "routes/_protected.ayuda.$module.$slug";
    page: "/ayuda/:module/:slug";
  };
  "routes/_protected.clientes.$id._index.tsx": {
    id: "routes/_protected.clientes.$id._index";
    page: "/clientes/:id";
  };
  "routes/_protected.proveedores._index.tsx": {
    id: "routes/_protected.proveedores._index";
    page: "/proveedores";
  };
  "routes/_protected.whatsapp.historial.tsx": {
    id: "routes/_protected.whatsapp.historial";
    page: "/whatsapp/historial";
  };
  "routes/_protected.clientes.$id.edit.tsx": {
    id: "routes/_protected.clientes.$id.edit";
    page: "/clientes/:id/edit";
  };
  "routes/_protected.proveedores.nuevo.tsx": {
    id: "routes/_protected.proveedores.nuevo";
    page: "/proveedores/nuevo";
  };
  "routes/_protected.ventas.$id._index.tsx": {
    id: "routes/_protected.ventas.$id._index";
    page: "/ventas/:id";
  };
  "routes/_protected.ventas.$id.editar.tsx": {
    id: "routes/_protected.ventas.$id.editar";
    page: "/ventas/:id/editar" | "/ventas/:id/editar/calculadora";
  };
  "routes/_protected.ventas.$id.editar.calculadora.tsx": {
    id: "routes/_protected.ventas.$id.editar.calculadora";
    page: "/ventas/:id/editar/calculadora";
  };
  "routes/_protected.ventas.$id.editar._index.tsx": {
    id: "routes/_protected.ventas.$id.editar._index";
    page: "/ventas/:id/editar";
  };
  "routes/_protected.productos._index.tsx": {
    id: "routes/_protected.productos._index";
    page: "/productos";
  };
  "routes/_protected.business.create.tsx": {
    id: "routes/_protected.business.create";
    page: "/business/create";
  };
  "routes/_protected.clientes._index.tsx": {
    id: "routes/_protected.clientes._index";
    page: "/clientes";
  };
  "routes/_protected.mi-distribucion.tsx": {
    id: "routes/_protected.mi-distribucion";
    page: "/mi-distribucion";
  };
  "routes/_protected.productos.nuevo.tsx": {
    id: "routes/_protected.productos.nuevo";
    page: "/productos/nuevo";
  };
  "routes/_protected.clientes.nuevo.tsx": {
    id: "routes/_protected.clientes.nuevo";
    page: "/clientes/nuevo";
  };
  "routes/_protected.distribuciones.tsx": {
    id: "routes/_protected.distribuciones";
    page: "/distribuciones" | "/distribuciones/:id/editar" | "/distribuciones/nueva";
  };
  "routes/_protected.distribuciones.$id.editar._index.tsx": {
    id: "routes/_protected.distribuciones.$id.editar._index";
    page: "/distribuciones/:id/editar";
  };
  "routes/_protected.distribuciones.nueva._index.tsx": {
    id: "routes/_protected.distribuciones.nueva._index";
    page: "/distribuciones/nueva";
  };
  "routes/_protected.business.edit.tsx": {
    id: "routes/_protected.business.edit";
    page: "/business/edit";
  };
  "routes/_protected.cobros._index.tsx": {
    id: "routes/_protected.cobros._index";
    page: "/cobros";
  };
  "routes/_protected.productos.$id.tsx": {
    id: "routes/_protected.productos.$id";
    page: "/productos/:id";
  };
  "routes/_protected.ventas._index.tsx": {
    id: "routes/_protected.ventas._index";
    page: "/ventas";
  };
  "routes/_protected.ayuda._index.tsx": {
    id: "routes/_protected.ayuda._index";
    page: "/ayuda";
  };
  "routes/_protected.cobros.nuevo.tsx": {
    id: "routes/_protected.cobros.nuevo";
    page: "/cobros/nuevo";
  };
  "routes/_protected.invitations.tsx": {
    id: "routes/_protected.invitations";
    page: "/invitations";
  };
  "routes/_protected.dashboard.tsx": {
    id: "routes/_protected.dashboard";
    page: "/dashboard";
  };
  "routes/_protected.activos.tsx": {
    id: "routes/_protected.activos";
    page: "/activos";
  };
  "routes/_protected.compras.tsx": {
    id: "routes/_protected.compras";
    page: "/compras" | "/compras/nueva" | "/compras/nueva/:draftId?/calculadora" | "/compras/nueva/:draftId?" | "/compras/:id" | "/compras/:id/editar" | "/compras/:id/editar/calculadora";
  };
  "routes/_protected.compras._index.tsx": {
    id: "routes/_protected.compras._index";
    page: "/compras";
  };
  "routes/_protected.compras.nueva.tsx": {
    id: "routes/_protected.compras.nueva";
    page: "/compras/nueva" | "/compras/nueva/:draftId?/calculadora" | "/compras/nueva/:draftId?";
  };
  "routes/_protected.compras.nueva.($draftId).calculadora.tsx": {
    id: "routes/_protected.compras.nueva.($draftId).calculadora";
    page: "/compras/nueva/:draftId?/calculadora";
  };
  "routes/_protected.compras.nueva.($draftId)._index.tsx": {
    id: "routes/_protected.compras.nueva.($draftId)._index";
    page: "/compras/nueva/:draftId?";
  };
  "routes/_protected.compras.$id.tsx": {
    id: "routes/_protected.compras.$id";
    page: "/compras/:id" | "/compras/:id/editar" | "/compras/:id/editar/calculadora";
  };
  "routes/_protected.compras.$id.editar.tsx": {
    id: "routes/_protected.compras.$id.editar";
    page: "/compras/:id/editar" | "/compras/:id/editar/calculadora";
  };
  "routes/_protected.compras.$id.editar.calculadora.tsx": {
    id: "routes/_protected.compras.$id.editar.calculadora";
    page: "/compras/:id/editar/calculadora";
  };
  "routes/_protected.compras.$id.editar._index.tsx": {
    id: "routes/_protected.compras.$id.editar._index";
    page: "/compras/:id/editar";
  };
  "routes/_protected.profile.tsx": {
    id: "routes/_protected.profile";
    page: "/profile";
  };
  "routes/_protected.visitas.tsx": {
    id: "routes/_protected.visitas";
    page: "/visitas";
  };
  "routes/_protected.cierre.tsx": {
    id: "routes/_protected.cierre";
    page: "/cierre";
  };
  "routes/_protected.config.tsx": {
    id: "routes/_protected.config";
    page: "/config" | "/config/payment-methods" | "/config/notifications" | "/config/puntos-venta" | "/config/appearance" | "/config/conflictos" | "/config/security" | "/config/whatsapp" | "/config/whatsapp/templates" | "/config/flags" | "/config/tags";
  };
  "routes/_protected.config.payment-methods.tsx": {
    id: "routes/_protected.config.payment-methods";
    page: "/config/payment-methods";
  };
  "routes/_protected.config.notifications.tsx": {
    id: "routes/_protected.config.notifications";
    page: "/config/notifications";
  };
  "routes/_protected.config.puntos-venta.tsx": {
    id: "routes/_protected.config.puntos-venta";
    page: "/config/puntos-venta";
  };
  "routes/_protected.config.appearance.tsx": {
    id: "routes/_protected.config.appearance";
    page: "/config/appearance";
  };
  "routes/_protected.config.conflictos.tsx": {
    id: "routes/_protected.config.conflictos";
    page: "/config/conflictos";
  };
  "routes/_protected.config.security.tsx": {
    id: "routes/_protected.config.security";
    page: "/config/security";
  };
  "routes/_protected.config.whatsapp.tsx": {
    id: "routes/_protected.config.whatsapp";
    page: "/config/whatsapp" | "/config/whatsapp/templates";
  };
  "routes/_protected.config.whatsapp.templates.tsx": {
    id: "routes/_protected.config.whatsapp.templates";
    page: "/config/whatsapp/templates";
  };
  "routes/_protected.config._index.tsx": {
    id: "routes/_protected.config._index";
    page: "/config";
  };
  "routes/_protected.config.flags.tsx": {
    id: "routes/_protected.config.flags";
    page: "/config/flags";
  };
  "routes/_protected.config.tags.tsx": {
    id: "routes/_protected.config.tags";
    page: "/config/tags";
  };
  "routes/_protected.grupos.tsx": {
    id: "routes/_protected.grupos";
    page: "/grupos";
  };
  "routes/_protected.team.tsx": {
    id: "routes/_protected.team";
    page: "/team";
  };
  "routes/landing.tsx": {
    id: "routes/landing";
    page: "/landing";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/sync.tsx": {
    id: "routes/sync";
    page: "/sync";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/invitations.$token": typeof import("./app/routes/invitations.$token.tsx");
  "routes/venta.$token": typeof import("./app/routes/venta.$token.tsx");
  "routes/_protected": typeof import("./app/routes/_protected.tsx");
  "routes/_protected.reportes.cuentas-por-cobrar": typeof import("./app/routes/_protected.reportes.cuentas-por-cobrar.tsx");
  "routes/_protected.reportes.compras-sugeridas": typeof import("./app/routes/_protected.reportes.compras-sugeridas.tsx");
  "routes/_protected.proveedores.$id._index": typeof import("./app/routes/_protected.proveedores.$id._index.tsx");
  "routes/_protected.proveedores.$id.edit": typeof import("./app/routes/_protected.proveedores.$id.edit.tsx");
  "routes/_protected.ayuda.$module.$slug": typeof import("./app/routes/_protected.ayuda.$module.$slug.tsx");
  "routes/_protected.clientes.$id._index": typeof import("./app/routes/_protected.clientes.$id._index.tsx");
  "routes/_protected.proveedores._index": typeof import("./app/routes/_protected.proveedores._index.tsx");
  "routes/_protected.whatsapp.historial": typeof import("./app/routes/_protected.whatsapp.historial.tsx");
  "routes/_protected.clientes.$id.edit": typeof import("./app/routes/_protected.clientes.$id.edit.tsx");
  "routes/_protected.proveedores.nuevo": typeof import("./app/routes/_protected.proveedores.nuevo.tsx");
  "routes/_protected.ventas.$id._index": typeof import("./app/routes/_protected.ventas.$id._index.tsx");
  "routes/_protected.ventas.$id.editar": typeof import("./app/routes/_protected.ventas.$id.editar.tsx");
  "routes/_protected.ventas.$id.editar.calculadora": typeof import("./app/routes/_protected.ventas.$id.editar.calculadora.tsx");
  "routes/_protected.ventas.$id.editar._index": typeof import("./app/routes/_protected.ventas.$id.editar._index.tsx");
  "routes/_protected.productos._index": typeof import("./app/routes/_protected.productos._index.tsx");
  "routes/_protected.business.create": typeof import("./app/routes/_protected.business.create.tsx");
  "routes/_protected.clientes._index": typeof import("./app/routes/_protected.clientes._index.tsx");
  "routes/_protected.mi-distribucion": typeof import("./app/routes/_protected.mi-distribucion.tsx");
  "routes/_protected.productos.nuevo": typeof import("./app/routes/_protected.productos.nuevo.tsx");
  "routes/_protected.clientes.nuevo": typeof import("./app/routes/_protected.clientes.nuevo.tsx");
  "routes/_protected.distribuciones": typeof import("./app/routes/_protected.distribuciones.tsx");
  "routes/_protected.distribuciones.$id.editar._index": typeof import("./app/routes/_protected.distribuciones.$id.editar._index.tsx");
  "routes/_protected.distribuciones.nueva._index": typeof import("./app/routes/_protected.distribuciones.nueva._index.tsx");
  "routes/_protected.business.edit": typeof import("./app/routes/_protected.business.edit.tsx");
  "routes/_protected.cobros._index": typeof import("./app/routes/_protected.cobros._index.tsx");
  "routes/_protected.productos.$id": typeof import("./app/routes/_protected.productos.$id.tsx");
  "routes/_protected.ventas._index": typeof import("./app/routes/_protected.ventas._index.tsx");
  "routes/_protected.ayuda._index": typeof import("./app/routes/_protected.ayuda._index.tsx");
  "routes/_protected.cobros.nuevo": typeof import("./app/routes/_protected.cobros.nuevo.tsx");
  "routes/_protected.invitations": typeof import("./app/routes/_protected.invitations.tsx");
  "routes/_protected.dashboard": typeof import("./app/routes/_protected.dashboard.tsx");
  "routes/_protected.activos": typeof import("./app/routes/_protected.activos.tsx");
  "routes/_protected.compras": typeof import("./app/routes/_protected.compras.tsx");
  "routes/_protected.compras._index": typeof import("./app/routes/_protected.compras._index.tsx");
  "routes/_protected.compras.nueva": typeof import("./app/routes/_protected.compras.nueva.tsx");
  "routes/_protected.compras.nueva.($draftId).calculadora": typeof import("./app/routes/_protected.compras.nueva.($draftId).calculadora.tsx");
  "routes/_protected.compras.nueva.($draftId)._index": typeof import("./app/routes/_protected.compras.nueva.($draftId)._index.tsx");
  "routes/_protected.compras.$id": typeof import("./app/routes/_protected.compras.$id.tsx");
  "routes/_protected.compras.$id.editar": typeof import("./app/routes/_protected.compras.$id.editar.tsx");
  "routes/_protected.compras.$id.editar.calculadora": typeof import("./app/routes/_protected.compras.$id.editar.calculadora.tsx");
  "routes/_protected.compras.$id.editar._index": typeof import("./app/routes/_protected.compras.$id.editar._index.tsx");
  "routes/_protected.profile": typeof import("./app/routes/_protected.profile.tsx");
  "routes/_protected.visitas": typeof import("./app/routes/_protected.visitas.tsx");
  "routes/_protected.cierre": typeof import("./app/routes/_protected.cierre.tsx");
  "routes/_protected.config": typeof import("./app/routes/_protected.config.tsx");
  "routes/_protected.config.payment-methods": typeof import("./app/routes/_protected.config.payment-methods.tsx");
  "routes/_protected.config.notifications": typeof import("./app/routes/_protected.config.notifications.tsx");
  "routes/_protected.config.puntos-venta": typeof import("./app/routes/_protected.config.puntos-venta.tsx");
  "routes/_protected.config.appearance": typeof import("./app/routes/_protected.config.appearance.tsx");
  "routes/_protected.config.conflictos": typeof import("./app/routes/_protected.config.conflictos.tsx");
  "routes/_protected.config.security": typeof import("./app/routes/_protected.config.security.tsx");
  "routes/_protected.config.whatsapp": typeof import("./app/routes/_protected.config.whatsapp.tsx");
  "routes/_protected.config.whatsapp.templates": typeof import("./app/routes/_protected.config.whatsapp.templates.tsx");
  "routes/_protected.config._index": typeof import("./app/routes/_protected.config._index.tsx");
  "routes/_protected.config.flags": typeof import("./app/routes/_protected.config.flags.tsx");
  "routes/_protected.config.tags": typeof import("./app/routes/_protected.config.tags.tsx");
  "routes/_protected.grupos": typeof import("./app/routes/_protected.grupos.tsx");
  "routes/_protected.team": typeof import("./app/routes/_protected.team.tsx");
  "routes/landing": typeof import("./app/routes/landing.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/sync": typeof import("./app/routes/sync.tsx");
};