// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/invitations/:token": {
    params: {
      "token": string;
    };
  };
  "/reportes/cuentas-por-cobrar": {
    params: {};
  };
  "/clientes/:id": {
    params: {
      "id": string;
    };
  };
  "/pedidos/:id": {
    params: {
      "id": string;
    };
  };
  "/proveedores": {
    params: {};
  };
  "/clientes/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/proveedores/nuevo": {
    params: {};
  };
  "/ventas/:id": {
    params: {
      "id": string;
    };
  };
  "/productos": {
    params: {};
  };
  "/business/create": {
    params: {};
  };
  "/clientes": {
    params: {};
  };
  "/mi-distribucion": {
    params: {};
  };
  "/productos/nuevo": {
    params: {};
  };
  "/clientes/nuevo": {
    params: {};
  };
  "/compras": {
    params: {};
  };
  "/distribuciones": {
    params: {};
  };
  "/pedidos": {
    params: {};
  };
  "/business/edit": {
    params: {};
  };
  "/cobros": {
    params: {};
  };
  "/compras/nueva": {
    params: {};
  };
  "/pedidos/nuevo": {
    params: {};
  };
  "/productos/:id": {
    params: {
      "id": string;
    };
  };
  "/ventas": {
    params: {};
  };
  "/cobros/nuevo": {
    params: {};
  };
  "/ventas/nueva": {
    params: {};
  };
  "/ventas/nueva/test": {
    params: {};
  };
  "/compras/:id": {
    params: {
      "id": string;
    };
  };
  "/invitations": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/activos": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/cierre": {
    params: {};
  };
  "/config": {
    params: {};
  };
  "/config/payment-methods": {
    params: {};
  };
  "/config/notifications": {
    params: {};
  };
  "/config/appearance": {
    params: {};
  };
  "/config/inventory": {
    params: {};
  };
  "/config/security": {
    params: {};
  };
  "/team": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/invitations/:token" | "/reportes/cuentas-por-cobrar" | "/clientes/:id" | "/pedidos/:id" | "/proveedores" | "/clientes/:id/edit" | "/proveedores/nuevo" | "/ventas/:id" | "/productos" | "/business/create" | "/clientes" | "/mi-distribucion" | "/productos/nuevo" | "/clientes/nuevo" | "/compras" | "/distribuciones" | "/pedidos" | "/business/edit" | "/cobros" | "/compras/nueva" | "/pedidos/nuevo" | "/productos/:id" | "/ventas" | "/cobros/nuevo" | "/ventas/nueva" | "/ventas/nueva/test" | "/compras/:id" | "/invitations" | "/dashboard" | "/activos" | "/profile" | "/cierre" | "/config" | "/config/payment-methods" | "/config/notifications" | "/config/appearance" | "/config/inventory" | "/config/security" | "/team" | "/register" | "/login";
  };
  "routes/invitations.$token.tsx": {
    id: "routes/invitations.$token";
    page: "/invitations/:token";
  };
  "routes/_protected.tsx": {
    id: "routes/_protected";
    page: "/reportes/cuentas-por-cobrar" | "/clientes/:id" | "/pedidos/:id" | "/proveedores" | "/clientes/:id/edit" | "/proveedores/nuevo" | "/ventas/:id" | "/productos" | "/business/create" | "/clientes" | "/mi-distribucion" | "/productos/nuevo" | "/clientes/nuevo" | "/compras" | "/distribuciones" | "/pedidos" | "/business/edit" | "/cobros" | "/compras/nueva" | "/pedidos/nuevo" | "/productos/:id" | "/ventas" | "/cobros/nuevo" | "/ventas/nueva" | "/ventas/nueva/test" | "/compras/:id" | "/invitations" | "/dashboard" | "/activos" | "/profile" | "/cierre" | "/config" | "/config/payment-methods" | "/config/notifications" | "/config/appearance" | "/config/inventory" | "/config/security" | "/team";
  };
  "routes/_protected.reportes.cuentas-por-cobrar.tsx": {
    id: "routes/_protected.reportes.cuentas-por-cobrar";
    page: "/reportes/cuentas-por-cobrar";
  };
  "routes/_protected.clientes.$id._index.tsx": {
    id: "routes/_protected.clientes.$id._index";
    page: "/clientes/:id";
  };
  "routes/_protected.pedidos.$id._index.tsx": {
    id: "routes/_protected.pedidos.$id._index";
    page: "/pedidos/:id";
  };
  "routes/_protected.proveedores._index.tsx": {
    id: "routes/_protected.proveedores._index";
    page: "/proveedores";
  };
  "routes/_protected.clientes.$id.edit.tsx": {
    id: "routes/_protected.clientes.$id.edit";
    page: "/clientes/:id/edit";
  };
  "routes/_protected.proveedores.nuevo.tsx": {
    id: "routes/_protected.proveedores.nuevo";
    page: "/proveedores/nuevo";
  };
  "routes/_protected.ventas.$id._index.tsx": {
    id: "routes/_protected.ventas.$id._index";
    page: "/ventas/:id";
  };
  "routes/_protected.productos._index.tsx": {
    id: "routes/_protected.productos._index";
    page: "/productos";
  };
  "routes/_protected.business.create.tsx": {
    id: "routes/_protected.business.create";
    page: "/business/create";
  };
  "routes/_protected.clientes._index.tsx": {
    id: "routes/_protected.clientes._index";
    page: "/clientes";
  };
  "routes/_protected.mi-distribucion.tsx": {
    id: "routes/_protected.mi-distribucion";
    page: "/mi-distribucion";
  };
  "routes/_protected.productos.nuevo.tsx": {
    id: "routes/_protected.productos.nuevo";
    page: "/productos/nuevo";
  };
  "routes/_protected.clientes.nuevo.tsx": {
    id: "routes/_protected.clientes.nuevo";
    page: "/clientes/nuevo";
  };
  "routes/_protected.compras._index.tsx": {
    id: "routes/_protected.compras._index";
    page: "/compras";
  };
  "routes/_protected.distribuciones.tsx": {
    id: "routes/_protected.distribuciones";
    page: "/distribuciones";
  };
  "routes/_protected.pedidos._index.tsx": {
    id: "routes/_protected.pedidos._index";
    page: "/pedidos";
  };
  "routes/_protected.business.edit.tsx": {
    id: "routes/_protected.business.edit";
    page: "/business/edit";
  };
  "routes/_protected.cobros._index.tsx": {
    id: "routes/_protected.cobros._index";
    page: "/cobros";
  };
  "routes/_protected.compras.nueva.tsx": {
    id: "routes/_protected.compras.nueva";
    page: "/compras/nueva";
  };
  "routes/_protected.pedidos.nuevo.tsx": {
    id: "routes/_protected.pedidos.nuevo";
    page: "/pedidos/nuevo";
  };
  "routes/_protected.productos.$id.tsx": {
    id: "routes/_protected.productos.$id";
    page: "/productos/:id";
  };
  "routes/_protected.ventas._index.tsx": {
    id: "routes/_protected.ventas._index";
    page: "/ventas";
  };
  "routes/_protected.cobros.nuevo.tsx": {
    id: "routes/_protected.cobros.nuevo";
    page: "/cobros/nuevo";
  };
  "routes/_protected.ventas.nueva.tsx": {
    id: "routes/_protected.ventas.nueva";
    page: "/ventas/nueva" | "/ventas/nueva/test";
  };
  "routes/_protected.ventas.nueva.test.tsx": {
    id: "routes/_protected.ventas.nueva.test";
    page: "/ventas/nueva/test";
  };
  "routes/_protected.compras.$id.tsx": {
    id: "routes/_protected.compras.$id";
    page: "/compras/:id";
  };
  "routes/_protected.invitations.tsx": {
    id: "routes/_protected.invitations";
    page: "/invitations";
  };
  "routes/_protected.dashboard.tsx": {
    id: "routes/_protected.dashboard";
    page: "/dashboard";
  };
  "routes/_protected.activos.tsx": {
    id: "routes/_protected.activos";
    page: "/activos";
  };
  "routes/_protected.profile.tsx": {
    id: "routes/_protected.profile";
    page: "/profile";
  };
  "routes/_protected.cierre.tsx": {
    id: "routes/_protected.cierre";
    page: "/cierre";
  };
  "routes/_protected.config.tsx": {
    id: "routes/_protected.config";
    page: "/config" | "/config/payment-methods" | "/config/notifications" | "/config/appearance" | "/config/inventory" | "/config/security";
  };
  "routes/_protected.config.payment-methods.tsx": {
    id: "routes/_protected.config.payment-methods";
    page: "/config/payment-methods";
  };
  "routes/_protected.config.notifications.tsx": {
    id: "routes/_protected.config.notifications";
    page: "/config/notifications";
  };
  "routes/_protected.config.appearance.tsx": {
    id: "routes/_protected.config.appearance";
    page: "/config/appearance";
  };
  "routes/_protected.config.inventory.tsx": {
    id: "routes/_protected.config.inventory";
    page: "/config/inventory";
  };
  "routes/_protected.config.security.tsx": {
    id: "routes/_protected.config.security";
    page: "/config/security";
  };
  "routes/_protected.config._index.tsx": {
    id: "routes/_protected.config._index";
    page: "/config";
  };
  "routes/_protected.team.tsx": {
    id: "routes/_protected.team";
    page: "/team";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/invitations.$token": typeof import("./app/routes/invitations.$token.tsx");
  "routes/_protected": typeof import("./app/routes/_protected.tsx");
  "routes/_protected.reportes.cuentas-por-cobrar": typeof import("./app/routes/_protected.reportes.cuentas-por-cobrar.tsx");
  "routes/_protected.clientes.$id._index": typeof import("./app/routes/_protected.clientes.$id._index.tsx");
  "routes/_protected.pedidos.$id._index": typeof import("./app/routes/_protected.pedidos.$id._index.tsx");
  "routes/_protected.proveedores._index": typeof import("./app/routes/_protected.proveedores._index.tsx");
  "routes/_protected.clientes.$id.edit": typeof import("./app/routes/_protected.clientes.$id.edit.tsx");
  "routes/_protected.proveedores.nuevo": typeof import("./app/routes/_protected.proveedores.nuevo.tsx");
  "routes/_protected.ventas.$id._index": typeof import("./app/routes/_protected.ventas.$id._index.tsx");
  "routes/_protected.productos._index": typeof import("./app/routes/_protected.productos._index.tsx");
  "routes/_protected.business.create": typeof import("./app/routes/_protected.business.create.tsx");
  "routes/_protected.clientes._index": typeof import("./app/routes/_protected.clientes._index.tsx");
  "routes/_protected.mi-distribucion": typeof import("./app/routes/_protected.mi-distribucion.tsx");
  "routes/_protected.productos.nuevo": typeof import("./app/routes/_protected.productos.nuevo.tsx");
  "routes/_protected.clientes.nuevo": typeof import("./app/routes/_protected.clientes.nuevo.tsx");
  "routes/_protected.compras._index": typeof import("./app/routes/_protected.compras._index.tsx");
  "routes/_protected.distribuciones": typeof import("./app/routes/_protected.distribuciones.tsx");
  "routes/_protected.pedidos._index": typeof import("./app/routes/_protected.pedidos._index.tsx");
  "routes/_protected.business.edit": typeof import("./app/routes/_protected.business.edit.tsx");
  "routes/_protected.cobros._index": typeof import("./app/routes/_protected.cobros._index.tsx");
  "routes/_protected.compras.nueva": typeof import("./app/routes/_protected.compras.nueva.tsx");
  "routes/_protected.pedidos.nuevo": typeof import("./app/routes/_protected.pedidos.nuevo.tsx");
  "routes/_protected.productos.$id": typeof import("./app/routes/_protected.productos.$id.tsx");
  "routes/_protected.ventas._index": typeof import("./app/routes/_protected.ventas._index.tsx");
  "routes/_protected.cobros.nuevo": typeof import("./app/routes/_protected.cobros.nuevo.tsx");
  "routes/_protected.ventas.nueva": typeof import("./app/routes/_protected.ventas.nueva.tsx");
  "routes/_protected.ventas.nueva.test": typeof import("./app/routes/_protected.ventas.nueva.test.tsx");
  "routes/_protected.compras.$id": typeof import("./app/routes/_protected.compras.$id.tsx");
  "routes/_protected.invitations": typeof import("./app/routes/_protected.invitations.tsx");
  "routes/_protected.dashboard": typeof import("./app/routes/_protected.dashboard.tsx");
  "routes/_protected.activos": typeof import("./app/routes/_protected.activos.tsx");
  "routes/_protected.profile": typeof import("./app/routes/_protected.profile.tsx");
  "routes/_protected.cierre": typeof import("./app/routes/_protected.cierre.tsx");
  "routes/_protected.config": typeof import("./app/routes/_protected.config.tsx");
  "routes/_protected.config.payment-methods": typeof import("./app/routes/_protected.config.payment-methods.tsx");
  "routes/_protected.config.notifications": typeof import("./app/routes/_protected.config.notifications.tsx");
  "routes/_protected.config.appearance": typeof import("./app/routes/_protected.config.appearance.tsx");
  "routes/_protected.config.inventory": typeof import("./app/routes/_protected.config.inventory.tsx");
  "routes/_protected.config.security": typeof import("./app/routes/_protected.config.security.tsx");
  "routes/_protected.config._index": typeof import("./app/routes/_protected.config._index.tsx");
  "routes/_protected.team": typeof import("./app/routes/_protected.team.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
};