// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/invitations/:token": {
    params: {
      "token": string;
    };
  };
  "/reportes/cuentas-por-cobrar": {
    params: {};
  };
  "/clientes/:id": {
    params: {
      "id": string;
    };
  };
  "/clientes/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/productos": {
    params: {};
  };
  "/business/create": {
    params: {};
  };
  "/clientes": {
    params: {};
  };
  "/mi-distribucion": {
    params: {};
  };
  "/productos/nuevo": {
    params: {};
  };
  "/clientes/nuevo": {
    params: {};
  };
  "/distribuciones": {
    params: {};
  };
  "/business/edit": {
    params: {};
  };
  "/productos/:id": {
    params: {
      "id": string;
    };
  };
  "/calculadora": {
    params: {};
  };
  "/invitations": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/cierre": {
    params: {};
  };
  "/config": {
    params: {};
  };
  "/config/payment-methods": {
    params: {};
  };
  "/config/inventory": {
    params: {};
  };
  "/ventas": {
    params: {};
  };
  "/ventas/nueva": {
    params: {};
  };
  "/ventas/:id": {
    params: {
      "id": string;
    };
  };
  "/register": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/invitations/:token" | "/reportes/cuentas-por-cobrar" | "/clientes/:id" | "/clientes/:id/edit" | "/productos" | "/business/create" | "/clientes" | "/mi-distribucion" | "/productos/nuevo" | "/clientes/nuevo" | "/distribuciones" | "/business/edit" | "/productos/:id" | "/calculadora" | "/invitations" | "/dashboard" | "/profile" | "/cierre" | "/config" | "/config/payment-methods" | "/config/inventory" | "/ventas" | "/ventas/nueva" | "/ventas/:id" | "/register" | "/login";
  };
  "routes/invitations.$token.tsx": {
    id: "routes/invitations.$token";
    page: "/invitations/:token";
  };
  "routes/_protected.tsx": {
    id: "routes/_protected";
    page: "/reportes/cuentas-por-cobrar" | "/clientes/:id" | "/clientes/:id/edit" | "/productos" | "/business/create" | "/clientes" | "/mi-distribucion" | "/productos/nuevo" | "/clientes/nuevo" | "/distribuciones" | "/business/edit" | "/productos/:id" | "/calculadora" | "/invitations" | "/dashboard" | "/profile" | "/cierre" | "/config" | "/config/payment-methods" | "/config/inventory" | "/ventas" | "/ventas/nueva" | "/ventas/:id";
  };
  "routes/_protected.reportes.cuentas-por-cobrar.tsx": {
    id: "routes/_protected.reportes.cuentas-por-cobrar";
    page: "/reportes/cuentas-por-cobrar";
  };
  "routes/_protected.clientes.$id._index.tsx": {
    id: "routes/_protected.clientes.$id._index";
    page: "/clientes/:id";
  };
  "routes/_protected.clientes.$id.edit.tsx": {
    id: "routes/_protected.clientes.$id.edit";
    page: "/clientes/:id/edit";
  };
  "routes/_protected.productos._index.tsx": {
    id: "routes/_protected.productos._index";
    page: "/productos";
  };
  "routes/_protected.business.create.tsx": {
    id: "routes/_protected.business.create";
    page: "/business/create";
  };
  "routes/_protected.clientes._index.tsx": {
    id: "routes/_protected.clientes._index";
    page: "/clientes";
  };
  "routes/_protected.mi-distribucion.tsx": {
    id: "routes/_protected.mi-distribucion";
    page: "/mi-distribucion";
  };
  "routes/_protected.productos.nuevo.tsx": {
    id: "routes/_protected.productos.nuevo";
    page: "/productos/nuevo";
  };
  "routes/_protected.clientes.nuevo.tsx": {
    id: "routes/_protected.clientes.nuevo";
    page: "/clientes/nuevo";
  };
  "routes/_protected.distribuciones.tsx": {
    id: "routes/_protected.distribuciones";
    page: "/distribuciones";
  };
  "routes/_protected.business.edit.tsx": {
    id: "routes/_protected.business.edit";
    page: "/business/edit";
  };
  "routes/_protected.productos.$id.tsx": {
    id: "routes/_protected.productos.$id";
    page: "/productos/:id";
  };
  "routes/_protected.calculadora.tsx": {
    id: "routes/_protected.calculadora";
    page: "/calculadora";
  };
  "routes/_protected.invitations.tsx": {
    id: "routes/_protected.invitations";
    page: "/invitations";
  };
  "routes/_protected.dashboard.tsx": {
    id: "routes/_protected.dashboard";
    page: "/dashboard";
  };
  "routes/_protected.profile.tsx": {
    id: "routes/_protected.profile";
    page: "/profile";
  };
  "routes/_protected.cierre.tsx": {
    id: "routes/_protected.cierre";
    page: "/cierre";
  };
  "routes/_protected.config.tsx": {
    id: "routes/_protected.config";
    page: "/config" | "/config/payment-methods" | "/config/inventory";
  };
  "routes/_protected.config.payment-methods.tsx": {
    id: "routes/_protected.config.payment-methods";
    page: "/config/payment-methods";
  };
  "routes/_protected.config.inventory.tsx": {
    id: "routes/_protected.config.inventory";
    page: "/config/inventory";
  };
  "routes/_protected.ventas.tsx": {
    id: "routes/_protected.ventas";
    page: "/ventas" | "/ventas/nueva" | "/ventas/:id";
  };
  "routes/_protected.ventas.nueva.tsx": {
    id: "routes/_protected.ventas.nueva";
    page: "/ventas/nueva";
  };
  "routes/_protected.ventas.$id.tsx": {
    id: "routes/_protected.ventas.$id";
    page: "/ventas/:id";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/invitations.$token": typeof import("./app/routes/invitations.$token.tsx");
  "routes/_protected": typeof import("./app/routes/_protected.tsx");
  "routes/_protected.reportes.cuentas-por-cobrar": typeof import("./app/routes/_protected.reportes.cuentas-por-cobrar.tsx");
  "routes/_protected.clientes.$id._index": typeof import("./app/routes/_protected.clientes.$id._index.tsx");
  "routes/_protected.clientes.$id.edit": typeof import("./app/routes/_protected.clientes.$id.edit.tsx");
  "routes/_protected.productos._index": typeof import("./app/routes/_protected.productos._index.tsx");
  "routes/_protected.business.create": typeof import("./app/routes/_protected.business.create.tsx");
  "routes/_protected.clientes._index": typeof import("./app/routes/_protected.clientes._index.tsx");
  "routes/_protected.mi-distribucion": typeof import("./app/routes/_protected.mi-distribucion.tsx");
  "routes/_protected.productos.nuevo": typeof import("./app/routes/_protected.productos.nuevo.tsx");
  "routes/_protected.clientes.nuevo": typeof import("./app/routes/_protected.clientes.nuevo.tsx");
  "routes/_protected.distribuciones": typeof import("./app/routes/_protected.distribuciones.tsx");
  "routes/_protected.business.edit": typeof import("./app/routes/_protected.business.edit.tsx");
  "routes/_protected.productos.$id": typeof import("./app/routes/_protected.productos.$id.tsx");
  "routes/_protected.calculadora": typeof import("./app/routes/_protected.calculadora.tsx");
  "routes/_protected.invitations": typeof import("./app/routes/_protected.invitations.tsx");
  "routes/_protected.dashboard": typeof import("./app/routes/_protected.dashboard.tsx");
  "routes/_protected.profile": typeof import("./app/routes/_protected.profile.tsx");
  "routes/_protected.cierre": typeof import("./app/routes/_protected.cierre.tsx");
  "routes/_protected.config": typeof import("./app/routes/_protected.config.tsx");
  "routes/_protected.config.payment-methods": typeof import("./app/routes/_protected.config.payment-methods.tsx");
  "routes/_protected.config.inventory": typeof import("./app/routes/_protected.config.inventory.tsx");
  "routes/_protected.ventas": typeof import("./app/routes/_protected.ventas.tsx");
  "routes/_protected.ventas.nueva": typeof import("./app/routes/_protected.ventas.nueva.tsx");
  "routes/_protected.ventas.$id": typeof import("./app/routes/_protected.ventas.$id.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
};