import { writeFileSync, mkdirSync, existsSync } from "fs";
import type { SyncConfig } from "./types";
import { introspectTable, buildRelationGraph } from "./introspect";
import { generateZodSchema, generateZodSchemasFile } from "./generators/zod-generator";
import { generatePostgreSQLDDL, generatePostgreSQLDDLFile } from "./generators/postgres-ddl-generator";
import { generateApplierConfig, mergeApplierConfigs, generateApplierFile } from "./generators/applier-generator";
import { generateHooks, generateHooksFile } from "./generators/hooks-generator";

export interface GenerationResult {
  files: string[];
  changes: string[];
}

export interface GenerationOptions {
  outputDir: string;
}

export async function generateAll(
  config: SyncConfig,
  options: GenerationOptions
): Promise<GenerationResult> {
  const outputDir = options.outputDir;

  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  const files: string[] = [];
  const changes: string[] = [];

  const entityNames = Object.keys(config.entities);

  // Build relation graph
  const graph = buildRelationGraph(
    Object.fromEntries(
      Object.entries(config.entities).map(([name, entity]) => [name, { table: entity.table }])
    )
  );

  // 1. Generate Zod schemas
  const zodSchemas = entityNames.map((name) =>
    generateZodSchema(name, config.entities[name])
  );
  const zodFile = generateZodSchemasFile(zodSchemas);
  writeFileSync(`${outputDir}/schemas.ts`, zodFile);
  files.push(`${outputDir}/schemas.ts`);

  // 2. Generate DDL (PostgreSQL for PGlite)
  const ddlOutputs = entityNames.map((name) => generatePostgreSQLDDL(name, config.entities[name]));
  const ddlFile = generatePostgreSQLDDLFile(ddlOutputs);
  writeFileSync(`${outputDir}/init.sql`, ddlFile);
  files.push(`${outputDir}/init.sql`);

  // 3. Generate applier config
  const applierConfigs = entityNames.map((name) =>
    generateApplierConfig(name, config.entities[name])
  );
  const mergedApplier = mergeApplierConfigs(applierConfigs);

  // Get apply order from graph
  const applyOrder = entityNames.sort((a, b) => graph[a].priority - graph[b].priority);

  const applierFile = generateApplierFile(mergedApplier, applyOrder);
  writeFileSync(`${outputDir}/applier.ts`, applierFile);
  files.push(`${outputDir}/applier.ts`);

  // 4. Generate hooks
  const hooks = new Map<string, ReturnType<typeof generateHooks>>();
  for (const name of entityNames) {
    hooks.set(name, generateHooks(name, config.entities[name], config.entities));
  }
  const hooksFile = generateHooksFile(hooks, config.entities);
  writeFileSync(`${outputDir}/hooks.ts`, hooksFile);
  files.push(`${outputDir}/hooks.ts`);

  // 5. Generate types (exports from schemas)
  const typesFile = generateTypesFile(entityNames);
  writeFileSync(`${outputDir}/types.ts`, typesFile);
  files.push(`${outputDir}/types.ts`);

  // Detect changes
  for (const name of entityNames) {
    const columns = introspectTable(config.entities[name].table);
    changes.push(`${name}: ${columns.length} fields`);
  }

  return { files, changes };
}

function generateTypesFile(entityNames: string[]): string {
  const reExports = entityNames
    .map((name) => {
      const pascal = name.charAt(0).toUpperCase() + name.slice(1);
      return `export type { ${pascal}, Create${pascal}Input } from "./schemas";`;
    })
    .join("\n");

  return `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by drizzle-sync from backend schema

export type { z } from "zod";
${reExports}
`;
}
